/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) amon_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 3, 5, 6, 0, 1,
  2, 1, 2, 2};
static const casadi_int casadi_s3[12] = 
  {3, 3, 0, 1, 3, 6, 0, 0,
  1, 0, 1, 2};
static const casadi_int casadi_s4[3] = {18, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[3] = {1, 1, 1};
static const casadi_int casadi_s7[3] = {23, 1, 1};

static const casadi_real casadi_c0[9] = 
  {3.4393020000000003e-02, 0., 0., 0., 3.9167399999999998e-02, 0., 0., 0.,
  2.8093010000000002e-02};
static const casadi_real casadi_c1[3] = {-1., 0., 0.};
static const casadi_real casadi_c2[3] = {0., -3.5000000000000003e-02, -1.4000000000000001e-01};
static const casadi_real casadi_c3[3] = {1., 0., 0.};
static const casadi_real casadi_c4[3] = {0., 3.5000000000000003e-02, -1.4000000000000001e-01};
static const casadi_real casadi_c5[3] = {0., -1., 0.};
static const casadi_real casadi_c6[3] = {-3.5000000000000003e-02, 0., -1.4000000000000001e-01};
static const casadi_real casadi_c7[3] = {0., 1., 0.};
static const casadi_real casadi_c8[3] = {3.5000000000000003e-02, 0., -1.4000000000000001e-01};
static const casadi_real casadi_c9[3] = {0., -1.5000000000000000e-03, 0.};

static const casadi_real casadi_zeros[18] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* adj1_f:(i0[18],i1[5],i2,out_o0[18x1,0nz],adj_o0[18])->(adj_i0[18],adj_i1[5],adj_i2) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w000=w+4, w001, *w004=w+44, *w005=w+47, *w006=w+51, w007, w008, w009, w010, w011, *w012=w+59;
  casadi_real *w013=w+62, *w014=w+71, *w015=w+74, w016, w017, w018, w019, w020, w021, w022, w023, *w024=w+91;
  casadi_real w025, w026, w027, w028, w029, w030, w031, w032, w033, w034, w035, w036;
  casadi_real *w037=w+106, *w038=w+110, *w039=w+114, *w040=w+118, *w041=w+122, *w042=w+126, *w043=w+142, w044, w045, w046, w047, *w048=w+162;
  casadi_real w049, *w050=w+166, w051, w052, w053, w054, w055, w056, w057, w058, w059, w060;
  casadi_real *w061=w+179, w062, w063, w064, w065, w066, w067, w068, w069, w070, w071, w072;
  casadi_real w073, w074, w075, w076, w077, w078, w079, w080, w081, w082, w083, w084;
  casadi_real w085, w086, w087, w088, w089, w090, w091, w092, w093, w094, w095, w096;
  casadi_real w097, w098, w099, w100, w101, w102, w103, w104, w105, w106, w107, w108;
  casadi_real w109, w110, w111, w112, w113, w114, *w115=w+237;
  const casadi_real *cs, *ct, *ss, *wr002, *wr003, *wr004, *wr005, *wr006, *wr013, *wr014, *wr015, *wr037;
  /* #0: @0 = zeros(18x1) */
  casadi_clear(w000, 18);
  /* #1: @1 = 14.2857 */
  w001 = 1.4285714285714285e+01;
  /* #2: @2 = input[4][0] */
  wr002 = arg[4] ? arg[4] : casadi_zeros;
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11} = vertsplit(@2) */
  wr003 = wr002;
  wr004 = wr002+3;
  wr005 = wr002+6;
  wr006 = wr002+10;
  w007 = wr002[13];
  w008 = wr002[14];
  w009 = wr002[15];
  w010 = wr002[16];
  w011 = wr002[17];
  /* #4: @1 = (@1*@11) */
  w001 *= w011;
  /* #5: @11 = (-@1) */
  w011 = (- w001 );
  /* #6: (@0[17] += @11) */
  for (rr=w000+17, cs=(&w011); rr!=w000+18; rr+=1) *rr += *cs++;
  /* #7: @11 = 14.2857 */
  w011 = 1.4285714285714285e+01;
  /* #8: @11 = (@11*@10) */
  w011 *= w010;
  /* #9: @10 = (-@11) */
  w010 = (- w011 );
  /* #10: (@0[16] += @10) */
  for (rr=w000+16, cs=(&w010); rr!=w000+17; rr+=1) *rr += *cs++;
  /* #11: @10 = 14.2857 */
  w010 = 1.4285714285714285e+01;
  /* #12: @10 = (@10*@9) */
  w010 *= w009;
  /* #13: @9 = (-@10) */
  w009 = (- w010 );
  /* #14: (@0[15] += @9) */
  for (rr=w000+15, cs=(&w009); rr!=w000+16; rr+=1) *rr += *cs++;
  /* #15: @9 = 14.2857 */
  w009 = 1.4285714285714285e+01;
  /* #16: @9 = (@9*@8) */
  w009 *= w008;
  /* #17: @8 = (-@9) */
  w008 = (- w009 );
  /* #18: (@0[14] += @8) */
  for (rr=w000+14, cs=(&w008); rr!=w000+15; rr+=1) *rr += *cs++;
  /* #19: @12 = zeros(3x1) */
  casadi_clear(w012, 3);
  /* #20: @13 = 
  [[0.034393, 0, 0], 
   [0, 0.0391674, 0], 
   [0, 0, 0.028093]] */
  wr013 = casadi_c0;
  /* #21: @2 = input[0][0] */
  wr002 = arg[0] ? arg[0] : casadi_zeros;
  /* #22: @14 = @2[10:13] */
  wr014 = wr002+10;
  /* #23: @12 = mac(@13,@14,@12) */
  for (i=0, rr=w012; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr013+j, ct=wr014+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #24: @8 = @12[1] */
  for (rr=(&w008), cs=w012+1; cs!=w012+2; cs+=1) *rr++ = *cs;
  /* #25: @15 = 
  [[0.034393, 0, 0], 
   [0, 0.0391674, 0], 
   [0, 0, 0.028093]] */
  wr015 = casadi_c0;
  /* #26: @6 = (@15'\@6) */
  rr = w006;
  ss = wr015;
  casadi_copy(wr006, 3, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 1, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #27: @14 = (-@6) */
  for (i=0, rr=w014, cs=w006; i<3; ++i) *rr++ = (- *cs++ );
  /* #28: {@16, @17, @18} = vertsplit(@14) */
  w016 = w014[0];
  w017 = w014[1];
  w018 = w014[2];
  /* #29: @19 = (@8*@18) */
  w019  = (w008*w018);
  /* #30: @20 = @12[2] */
  for (rr=(&w020), cs=w012+2; cs!=w012+3; cs+=1) *rr++ = *cs;
  /* #31: @21 = (@20*@17) */
  w021  = (w020*w017);
  /* #32: @19 = (@19-@21) */
  w019 -= w021;
  /* #33: (@0[10] += @19) */
  for (rr=w000+10, cs=(&w019); rr!=w000+11; rr+=1) *rr += *cs++;
  /* #34: @19 = @12[0] */
  for (rr=(&w019), cs=w012+0; cs!=w012+1; cs+=1) *rr++ = *cs;
  /* #35: @21 = (@19*@17) */
  w021  = (w019*w017);
  /* #36: @8 = (@8*@16) */
  w008 *= w016;
  /* #37: @21 = (@21-@8) */
  w021 -= w008;
  /* #38: (@0[12] += @21) */
  for (rr=w000+12, cs=(&w021); rr!=w000+13; rr+=1) *rr += *cs++;
  /* #39: @12 = zeros(3x1) */
  casadi_clear(w012, 3);
  /* #40: @15 = @13' */
  for (i=0, rr=w015, cs=wr013; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #41: @14 = zeros(3x1) */
  casadi_clear(w014, 3);
  /* #42: @21 = @2[12] */
  w021 = wr002[12];
  /* #43: @8 = (@21*@17) */
  w008  = (w021*w017);
  /* #44: @22 = @2[11] */
  w022 = wr002[11];
  /* #45: @23 = (@22*@18) */
  w023  = (w022*w018);
  /* #46: @8 = (@8-@23) */
  w008 -= w023;
  /* #47: (@14[0] += @8) */
  for (rr=w014+0, cs=(&w008); rr!=w014+1; rr+=1) *rr += *cs++;
  /* #48: @8 = @2[10] */
  w008 = wr002[10];
  /* #49: @23 = (@8*@18) */
  w023  = (w008*w018);
  /* #50: @21 = (@21*@16) */
  w021 *= w016;
  /* #51: @23 = (@23-@21) */
  w023 -= w021;
  /* #52: (@14[1] += @23) */
  for (rr=w014+1, cs=(&w023); rr!=w014+2; rr+=1) *rr += *cs++;
  /* #53: @22 = (@22*@16) */
  w022 *= w016;
  /* #54: @8 = (@8*@17) */
  w008 *= w017;
  /* #55: @22 = (@22-@8) */
  w022 -= w008;
  /* #56: (@14[2] += @22) */
  for (rr=w014+2, cs=(&w022); rr!=w014+3; rr+=1) *rr += *cs++;
  /* #57: @12 = mac(@15,@14,@12) */
  for (i=0, rr=w012; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w015+j, ct=w014+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #58: (@0[10:13] += @12) */
  for (rr=w000+10, cs=w012; rr!=w000+13; rr+=1) *rr += *cs++;
  /* #59: @20 = (@20*@16) */
  w020 *= w016;
  /* #60: @19 = (@19*@18) */
  w019 *= w018;
  /* #61: @20 = (@20-@19) */
  w020 -= w019;
  /* #62: (@0[11] += @20) */
  for (rr=w000+11, cs=(&w020); rr!=w000+12; rr+=1) *rr += *cs++;
  /* #63: @20 = @2[17] */
  w020 = wr002[17];
  /* #64: @19 = cos(@20) */
  w019 = cos( w020 );
  /* #65: @18 = 0.067146 */
  w018 = 6.7145999999999997e-02;
  /* #66: @16 = @2[13] */
  w016 = wr002[13];
  /* #67: @22 = (@18*@16) */
  w022  = (w018*w016);
  /* #68: @12 = [-1, 0, 0] */
  casadi_copy(casadi_c1, 3, w012);
  /* #69: @14 = zeros(3x1) */
  casadi_clear(w014, 3);
  /* #70: @24 = [0, -0.035, -0.14] */
  casadi_copy(casadi_c2, 3, w024);
  /* #71: @8 = @24[2] */
  for (rr=(&w008), cs=w024+2; cs!=w024+3; cs+=1) *rr++ = *cs;
  /* #72: {@17, @23, @21} = vertsplit(@6) */
  w017 = w006[0];
  w023 = w006[1];
  w021 = w006[2];
  /* #73: @25 = (@8*@23) */
  w025  = (w008*w023);
  /* #74: @26 = @24[1] */
  for (rr=(&w026), cs=w024+1; cs!=w024+2; cs+=1) *rr++ = *cs;
  /* #75: @27 = (@26*@21) */
  w027  = (w026*w021);
  /* #76: @25 = (@25-@27) */
  w025 -= w027;
  /* #77: (@14[0] += @25) */
  for (rr=w014+0, cs=(&w025); rr!=w014+1; rr+=1) *rr += *cs++;
  /* #78: @25 = @24[0] */
  for (rr=(&w025), cs=w024+0; cs!=w024+1; cs+=1) *rr++ = *cs;
  /* #79: @21 = (@25*@21) */
  w021  = (w025*w021);
  /* #80: @8 = (@8*@17) */
  w008 *= w017;
  /* #81: @21 = (@21-@8) */
  w021 -= w008;
  /* #82: (@14[1] += @21) */
  for (rr=w014+1, cs=(&w021); rr!=w014+2; rr+=1) *rr += *cs++;
  /* #83: @26 = (@26*@17) */
  w026 *= w017;
  /* #84: @25 = (@25*@23) */
  w025 *= w023;
  /* #85: @26 = (@26-@25) */
  w026 -= w025;
  /* #86: (@14[2] += @26) */
  for (rr=w014+2, cs=(&w026); rr!=w014+3; rr+=1) *rr += *cs++;
  /* #87: @26 = dot(@12, @14) */
  w026 = casadi_dot(3, w012, w014);
  /* #88: @22 = (@22*@26) */
  w022 *= w026;
  /* #89: @19 = (@19*@22) */
  w019 *= w022;
  /* #90: (@0[17] += @19) */
  for (rr=w000+17, cs=(&w019); rr!=w000+18; rr+=1) *rr += *cs++;
  /* #91: @19 = @2[16] */
  w019 = wr002[16];
  /* #92: @22 = cos(@19) */
  w022 = cos( w019 );
  /* #93: @25 = 0.067146 */
  w025 = 6.7145999999999997e-02;
  /* #94: @23 = (@25*@16) */
  w023  = (w025*w016);
  /* #95: @12 = [1, 0, 0] */
  casadi_copy(casadi_c3, 3, w012);
  /* #96: @14 = zeros(3x1) */
  casadi_clear(w014, 3);
  /* #97: @24 = [0, 0.035, -0.14] */
  casadi_copy(casadi_c4, 3, w024);
  /* #98: @17 = @24[2] */
  for (rr=(&w017), cs=w024+2; cs!=w024+3; cs+=1) *rr++ = *cs;
  /* #99: {@21, @8, @27} = vertsplit(@6) */
  w021 = w006[0];
  w008 = w006[1];
  w027 = w006[2];
  /* #100: @28 = (@17*@8) */
  w028  = (w017*w008);
  /* #101: @29 = @24[1] */
  for (rr=(&w029), cs=w024+1; cs!=w024+2; cs+=1) *rr++ = *cs;
  /* #102: @30 = (@29*@27) */
  w030  = (w029*w027);
  /* #103: @28 = (@28-@30) */
  w028 -= w030;
  /* #104: (@14[0] += @28) */
  for (rr=w014+0, cs=(&w028); rr!=w014+1; rr+=1) *rr += *cs++;
  /* #105: @28 = @24[0] */
  for (rr=(&w028), cs=w024+0; cs!=w024+1; cs+=1) *rr++ = *cs;
  /* #106: @27 = (@28*@27) */
  w027  = (w028*w027);
  /* #107: @17 = (@17*@21) */
  w017 *= w021;
  /* #108: @27 = (@27-@17) */
  w027 -= w017;
  /* #109: (@14[1] += @27) */
  for (rr=w014+1, cs=(&w027); rr!=w014+2; rr+=1) *rr += *cs++;
  /* #110: @29 = (@29*@21) */
  w029 *= w021;
  /* #111: @28 = (@28*@8) */
  w028 *= w008;
  /* #112: @29 = (@29-@28) */
  w029 -= w028;
  /* #113: (@14[2] += @29) */
  for (rr=w014+2, cs=(&w029); rr!=w014+3; rr+=1) *rr += *cs++;
  /* #114: @29 = dot(@12, @14) */
  w029 = casadi_dot(3, w012, w014);
  /* #115: @23 = (@23*@29) */
  w023 *= w029;
  /* #116: @22 = (@22*@23) */
  w022 *= w023;
  /* #117: (@0[16] += @22) */
  for (rr=w000+16, cs=(&w022); rr!=w000+17; rr+=1) *rr += *cs++;
  /* #118: @22 = @2[15] */
  w022 = wr002[15];
  /* #119: @23 = cos(@22) */
  w023 = cos( w022 );
  /* #120: @28 = 0.067146 */
  w028 = 6.7145999999999997e-02;
  /* #121: @8 = (@28*@16) */
  w008  = (w028*w016);
  /* #122: @12 = [0, -1, 0] */
  casadi_copy(casadi_c5, 3, w012);
  /* #123: @14 = zeros(3x1) */
  casadi_clear(w014, 3);
  /* #124: @24 = [-0.035, 0, -0.14] */
  casadi_copy(casadi_c6, 3, w024);
  /* #125: @21 = @24[2] */
  for (rr=(&w021), cs=w024+2; cs!=w024+3; cs+=1) *rr++ = *cs;
  /* #126: {@27, @17, @30} = vertsplit(@6) */
  w027 = w006[0];
  w017 = w006[1];
  w030 = w006[2];
  /* #127: @31 = (@21*@17) */
  w031  = (w021*w017);
  /* #128: @32 = @24[1] */
  for (rr=(&w032), cs=w024+1; cs!=w024+2; cs+=1) *rr++ = *cs;
  /* #129: @33 = (@32*@30) */
  w033  = (w032*w030);
  /* #130: @31 = (@31-@33) */
  w031 -= w033;
  /* #131: (@14[0] += @31) */
  for (rr=w014+0, cs=(&w031); rr!=w014+1; rr+=1) *rr += *cs++;
  /* #132: @31 = @24[0] */
  for (rr=(&w031), cs=w024+0; cs!=w024+1; cs+=1) *rr++ = *cs;
  /* #133: @30 = (@31*@30) */
  w030  = (w031*w030);
  /* #134: @21 = (@21*@27) */
  w021 *= w027;
  /* #135: @30 = (@30-@21) */
  w030 -= w021;
  /* #136: (@14[1] += @30) */
  for (rr=w014+1, cs=(&w030); rr!=w014+2; rr+=1) *rr += *cs++;
  /* #137: @32 = (@32*@27) */
  w032 *= w027;
  /* #138: @31 = (@31*@17) */
  w031 *= w017;
  /* #139: @32 = (@32-@31) */
  w032 -= w031;
  /* #140: (@14[2] += @32) */
  for (rr=w014+2, cs=(&w032); rr!=w014+3; rr+=1) *rr += *cs++;
  /* #141: @32 = dot(@12, @14) */
  w032 = casadi_dot(3, w012, w014);
  /* #142: @8 = (@8*@32) */
  w008 *= w032;
  /* #143: @23 = (@23*@8) */
  w023 *= w008;
  /* #144: (@0[15] += @23) */
  for (rr=w000+15, cs=(&w023); rr!=w000+16; rr+=1) *rr += *cs++;
  /* #145: @23 = @2[14] */
  w023 = wr002[14];
  /* #146: @8 = cos(@23) */
  w008 = cos( w023 );
  /* #147: @31 = 0.067146 */
  w031 = 6.7145999999999997e-02;
  /* #148: @17 = (@31*@16) */
  w017  = (w031*w016);
  /* #149: @12 = [0, 1, 0] */
  casadi_copy(casadi_c7, 3, w012);
  /* #150: @14 = zeros(3x1) */
  casadi_clear(w014, 3);
  /* #151: @24 = [0.035, 0, -0.14] */
  casadi_copy(casadi_c8, 3, w024);
  /* #152: @27 = @24[2] */
  for (rr=(&w027), cs=w024+2; cs!=w024+3; cs+=1) *rr++ = *cs;
  /* #153: {@30, @21, @33} = vertsplit(@6) */
  w030 = w006[0];
  w021 = w006[1];
  w033 = w006[2];
  /* #154: @34 = (@27*@21) */
  w034  = (w027*w021);
  /* #155: @35 = @24[1] */
  for (rr=(&w035), cs=w024+1; cs!=w024+2; cs+=1) *rr++ = *cs;
  /* #156: @36 = (@35*@33) */
  w036  = (w035*w033);
  /* #157: @34 = (@34-@36) */
  w034 -= w036;
  /* #158: (@14[0] += @34) */
  for (rr=w014+0, cs=(&w034); rr!=w014+1; rr+=1) *rr += *cs++;
  /* #159: @34 = @24[0] */
  for (rr=(&w034), cs=w024+0; cs!=w024+1; cs+=1) *rr++ = *cs;
  /* #160: @33 = (@34*@33) */
  w033  = (w034*w033);
  /* #161: @27 = (@27*@30) */
  w027 *= w030;
  /* #162: @33 = (@33-@27) */
  w033 -= w027;
  /* #163: (@14[1] += @33) */
  for (rr=w014+1, cs=(&w033); rr!=w014+2; rr+=1) *rr += *cs++;
  /* #164: @35 = (@35*@30) */
  w035 *= w030;
  /* #165: @34 = (@34*@21) */
  w034 *= w021;
  /* #166: @35 = (@35-@34) */
  w035 -= w034;
  /* #167: (@14[2] += @35) */
  for (rr=w014+2, cs=(&w035); rr!=w014+3; rr+=1) *rr += *cs++;
  /* #168: @35 = dot(@12, @14) */
  w035 = casadi_dot(3, w012, w014);
  /* #169: @17 = (@17*@35) */
  w017 *= w035;
  /* #170: @8 = (@8*@17) */
  w008 *= w017;
  /* #171: (@0[14] += @8) */
  for (rr=w000+14, cs=(&w008); rr!=w000+15; rr+=1) *rr += *cs++;
  /* #172: @12 = [0, -0.0015, 0] */
  casadi_copy(casadi_c9, 3, w012);
  /* #173: @8 = @12[1] */
  for (rr=(&w008), cs=w012+1; cs!=w012+2; cs+=1) *rr++ = *cs;
  /* #174: {@17, @34, NULL} = vertsplit(@6) */
  w017 = w006[0];
  w034 = w006[1];
  /* #175: @8 = (@8*@17) */
  w008 *= w017;
  /* #176: @17 = @12[0] */
  for (rr=(&w017), cs=w012+0; cs!=w012+1; cs+=1) *rr++ = *cs;
  /* #177: @17 = (@17*@34) */
  w017 *= w034;
  /* #178: @8 = (@8-@17) */
  w008 -= w017;
  /* #179: (@0[13] += @8) */
  for (rr=w000+13, cs=(&w008); rr!=w000+14; rr+=1) *rr += *cs++;
  /* #180: @37 = zeros(4x1) */
  casadi_clear(w037, 4);
  /* #181: @8 = 0 */
  w008 = 0.;
  /* #182: @17 = @2[10] */
  w017 = wr002[10];
  /* #183: @34 = (-@17) */
  w034 = (- w017 );
  /* #184: @21 = @2[11] */
  w021 = wr002[11];
  /* #185: @30 = (-@21) */
  w030 = (- w021 );
  /* #186: @33 = @2[12] */
  w033 = wr002[12];
  /* #187: @27 = (-@33) */
  w027 = (- w033 );
  /* #188: @38 = horzcat(@8, @34, @30, @27) */
  rr=w038;
  *rr++ = w008;
  *rr++ = w034;
  *rr++ = w030;
  *rr++ = w027;
  /* #189: @38 = @38' */
  /* #190: @8 = 0 */
  w008 = 0.;
  /* #191: @34 = (-@21) */
  w034 = (- w021 );
  /* #192: @39 = horzcat(@17, @8, @33, @34) */
  rr=w039;
  *rr++ = w017;
  *rr++ = w008;
  *rr++ = w033;
  *rr++ = w034;
  /* #193: @39 = @39' */
  /* #194: @8 = (-@33) */
  w008 = (- w033 );
  /* #195: @34 = 0 */
  w034 = 0.;
  /* #196: @40 = horzcat(@21, @8, @34, @17) */
  rr=w040;
  *rr++ = w021;
  *rr++ = w008;
  *rr++ = w034;
  *rr++ = w017;
  /* #197: @40 = @40' */
  /* #198: @17 = (-@17) */
  w017 = (- w017 );
  /* #199: @8 = 0 */
  w008 = 0.;
  /* #200: @41 = horzcat(@33, @21, @17, @8) */
  rr=w041;
  *rr++ = w033;
  *rr++ = w021;
  *rr++ = w017;
  *rr++ = w008;
  /* #201: @41 = @41' */
  /* #202: @42 = horzcat(@38, @39, @40, @41) */
  rr=w042;
  for (i=0, cs=w038; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w039; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w040; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w041; i<4; ++i) *rr++ = *cs++;
  /* #203: @33 = 0.5 */
  w033 = 5.0000000000000000e-01;
  /* #204: @5 = (@33*@5) */
  for (i=0, rr=w005, cs=wr005; i<4; ++i) (*rr++)  = (w033*(*cs++));
  /* #205: @37 = mac(@42,@5,@37) */
  for (i=0, rr=w037; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w042+j, ct=w005+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #206: (@0[6:10] += @37) */
  for (rr=w000+6, cs=w037; rr!=w000+10; rr+=1) *rr += *cs++;
  /* #207: @42 = zeros(4x4) */
  casadi_clear(w042, 16);
  /* #208: @37 = @2[6:10] */
  wr037 = wr002+6;
  /* #209: @37 = @37' */
  /* #210: @42 = mac(@5,@37,@42) */
  for (i=0, rr=w042; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w005+j, ct=wr037+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #211: @43 = @42' */
  for (i=0, rr=w043, cs=w042; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #212: {@5, @37, @38, @39} = horzsplit(@43) */
  casadi_copy(w043, 4, w005);
  casadi_copy(w043+4, 4, w037);
  casadi_copy(w043+8, 4, w038);
  casadi_copy(w043+12, 4, w039);
  /* #213: @39 = @39' */
  /* #214: {@33, @21, @17, NULL} = horzsplit(@39) */
  w033 = w039[0];
  w021 = w039[1];
  w017 = w039[2];
  /* #215: @38 = @38' */
  /* #216: {@8, @34, NULL, @30} = horzsplit(@38) */
  w008 = w038[0];
  w034 = w038[1];
  w030 = w038[3];
  /* #217: @33 = (@33-@34) */
  w033 -= w034;
  /* #218: @37 = @37' */
  /* #219: {@34, NULL, @27, @36} = horzsplit(@37) */
  w034 = w037[0];
  w027 = w037[2];
  w036 = w037[3];
  /* #220: @33 = (@33+@27) */
  w033 += w027;
  /* #221: @5 = @5' */
  /* #222: {NULL, @27, @44, @45} = horzsplit(@5) */
  w027 = w005[1];
  w044 = w005[2];
  w045 = w005[3];
  /* #223: @33 = (@33-@45) */
  w033 -= w045;
  /* #224: (@0[12] += @33) */
  for (rr=w000+12, cs=(&w033); rr!=w000+13; rr+=1) *rr += *cs++;
  /* #225: @21 = (@21+@8) */
  w021 += w008;
  /* #226: @21 = (@21-@36) */
  w021 -= w036;
  /* #227: @21 = (@21-@44) */
  w021 -= w044;
  /* #228: (@0[11] += @21) */
  for (rr=w000+11, cs=(&w021); rr!=w000+12; rr+=1) *rr += *cs++;
  /* #229: @30 = (@30-@17) */
  w030 -= w017;
  /* #230: @30 = (@30+@34) */
  w030 += w034;
  /* #231: @30 = (@30-@27) */
  w030 -= w027;
  /* #232: (@0[10] += @30) */
  for (rr=w000+10, cs=(&w030); rr!=w000+11; rr+=1) *rr += *cs++;
  /* #233: @30 = @2[17] */
  w030 = wr002[17];
  /* #234: @27 = cos(@30) */
  w027 = cos( w030 );
  /* #235: @34 = 0.067146 */
  w034 = 6.7145999999999997e-02;
  /* #236: @17 = (@34*@16) */
  w017  = (w034*w016);
  /* #237: @12 = [-1, 0, 0] */
  casadi_copy(casadi_c1, 3, w012);
  /* #238: @14 = zeros(3x1) */
  casadi_clear(w014, 3);
  /* #239: @21 = 1 */
  w021 = 1.;
  /* #240: @44 = @2[8] */
  w044 = wr002[8];
  /* #241: @36 = sq(@44) */
  w036 = casadi_sq( w044 );
  /* #242: @8 = @2[9] */
  w008 = wr002[9];
  /* #243: @33 = sq(@8) */
  w033 = casadi_sq( w008 );
  /* #244: @36 = (@36+@33) */
  w036 += w033;
  /* #245: @36 = (2.*@36) */
  w036 = (2.* w036 );
  /* #246: @21 = (@21-@36) */
  w021 -= w036;
  /* #247: @36 = @2[7] */
  w036 = wr002[7];
  /* #248: @33 = (@36*@44) */
  w033  = (w036*w044);
  /* #249: @45 = @2[6] */
  w045 = wr002[6];
  /* #250: @46 = (@45*@8) */
  w046  = (w045*w008);
  /* #251: @33 = (@33-@46) */
  w033 -= w046;
  /* #252: @33 = (2.*@33) */
  w033 = (2.* w033 );
  /* #253: @46 = (@36*@8) */
  w046  = (w036*w008);
  /* #254: @47 = (@45*@44) */
  w047  = (w045*w044);
  /* #255: @46 = (@46+@47) */
  w046 += w047;
  /* #256: @46 = (2.*@46) */
  w046 = (2.* w046 );
  /* #257: @24 = horzcat(@21, @33, @46) */
  rr=w024;
  *rr++ = w021;
  *rr++ = w033;
  *rr++ = w046;
  /* #258: @24 = @24' */
  /* #259: @21 = (@36*@44) */
  w021  = (w036*w044);
  /* #260: @33 = (@45*@8) */
  w033  = (w045*w008);
  /* #261: @21 = (@21+@33) */
  w021 += w033;
  /* #262: @21 = (2.*@21) */
  w021 = (2.* w021 );
  /* #263: @33 = 1 */
  w033 = 1.;
  /* #264: @46 = sq(@36) */
  w046 = casadi_sq( w036 );
  /* #265: @47 = sq(@8) */
  w047 = casadi_sq( w008 );
  /* #266: @46 = (@46+@47) */
  w046 += w047;
  /* #267: @46 = (2.*@46) */
  w046 = (2.* w046 );
  /* #268: @33 = (@33-@46) */
  w033 -= w046;
  /* #269: @46 = (@44*@8) */
  w046  = (w044*w008);
  /* #270: @47 = (@45*@36) */
  w047  = (w045*w036);
  /* #271: @46 = (@46-@47) */
  w046 -= w047;
  /* #272: @46 = (2.*@46) */
  w046 = (2.* w046 );
  /* #273: @48 = horzcat(@21, @33, @46) */
  rr=w048;
  *rr++ = w021;
  *rr++ = w033;
  *rr++ = w046;
  /* #274: @48 = @48' */
  /* #275: @21 = (@36*@8) */
  w021  = (w036*w008);
  /* #276: @33 = (@45*@44) */
  w033  = (w045*w044);
  /* #277: @21 = (@21-@33) */
  w021 -= w033;
  /* #278: @21 = (2.*@21) */
  w021 = (2.* w021 );
  /* #279: @33 = (@44*@8) */
  w033  = (w044*w008);
  /* #280: @46 = (@45*@36) */
  w046  = (w045*w036);
  /* #281: @33 = (@33+@46) */
  w033 += w046;
  /* #282: @33 = (2.*@33) */
  w033 = (2.* w033 );
  /* #283: @46 = 1 */
  w046 = 1.;
  /* #284: @47 = sq(@36) */
  w047 = casadi_sq( w036 );
  /* #285: @49 = sq(@44) */
  w049 = casadi_sq( w044 );
  /* #286: @47 = (@47+@49) */
  w047 += w049;
  /* #287: @47 = (2.*@47) */
  w047 = (2.* w047 );
  /* #288: @46 = (@46-@47) */
  w046 -= w047;
  /* #289: @50 = horzcat(@21, @33, @46) */
  rr=w050;
  *rr++ = w021;
  *rr++ = w033;
  *rr++ = w046;
  /* #290: @50 = @50' */
  /* #291: @15 = horzcat(@24, @48, @50) */
  rr=w015;
  for (i=0, cs=w024; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w048; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w050; i<3; ++i) *rr++ = *cs++;
  /* #292: @21 = 0.402414 */
  w021 = 4.0241448692152920e-01;
  /* #293: @4 = (@21*@4) */
  for (i=0, rr=w004, cs=wr004; i<3; ++i) (*rr++)  = (w021*(*cs++));
  /* #294: @14 = mac(@15,@4,@14) */
  for (i=0, rr=w014; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w015+j, ct=w004+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #295: @21 = dot(@12, @14) */
  w021 = casadi_dot(3, w012, w014);
  /* #296: @33 = (@17*@21) */
  w033  = (w017*w021);
  /* #297: @27 = (@27*@33) */
  w027 *= w033;
  /* #298: (@0[17] += @27) */
  for (rr=w000+17, cs=(&w027); rr!=w000+18; rr+=1) *rr += *cs++;
  /* #299: @27 = @2[16] */
  w027 = wr002[16];
  /* #300: @33 = cos(@27) */
  w033 = cos( w027 );
  /* #301: @46 = 0.067146 */
  w046 = 6.7145999999999997e-02;
  /* #302: @47 = (@46*@16) */
  w047  = (w046*w016);
  /* #303: @24 = [1, 0, 0] */
  casadi_copy(casadi_c3, 3, w024);
  /* #304: @49 = dot(@24, @14) */
  w049 = casadi_dot(3, w024, w014);
  /* #305: @51 = (@47*@49) */
  w051  = (w047*w049);
  /* #306: @33 = (@33*@51) */
  w033 *= w051;
  /* #307: (@0[16] += @33) */
  for (rr=w000+16, cs=(&w033); rr!=w000+17; rr+=1) *rr += *cs++;
  /* #308: @33 = @2[15] */
  w033 = wr002[15];
  /* #309: @51 = cos(@33) */
  w051 = cos( w033 );
  /* #310: @52 = 0.067146 */
  w052 = 6.7145999999999997e-02;
  /* #311: @53 = (@52*@16) */
  w053  = (w052*w016);
  /* #312: @48 = [0, -1, 0] */
  casadi_copy(casadi_c5, 3, w048);
  /* #313: @54 = dot(@48, @14) */
  w054 = casadi_dot(3, w048, w014);
  /* #314: @55 = (@53*@54) */
  w055  = (w053*w054);
  /* #315: @51 = (@51*@55) */
  w051 *= w055;
  /* #316: (@0[15] += @51) */
  for (rr=w000+15, cs=(&w051); rr!=w000+16; rr+=1) *rr += *cs++;
  /* #317: @51 = @2[14] */
  w051 = wr002[14];
  /* #318: @55 = cos(@51) */
  w055 = cos( w051 );
  /* #319: @56 = 0.067146 */
  w056 = 6.7145999999999997e-02;
  /* #320: @57 = (@56*@16) */
  w057  = (w056*w016);
  /* #321: @50 = [0, 1, 0] */
  casadi_copy(casadi_c7, 3, w050);
  /* #322: @58 = dot(@50, @14) */
  w058 = casadi_dot(3, w050, w014);
  /* #323: @59 = (@57*@58) */
  w059  = (w057*w058);
  /* #324: @55 = (@55*@59) */
  w055 *= w059;
  /* #325: (@0[14] += @55) */
  for (rr=w000+14, cs=(&w055); rr!=w000+15; rr+=1) *rr += *cs++;
  /* #326: @55 = -0.00066188 */
  w055 = -6.6188000000000000e-04;
  /* #327: {NULL, NULL, @59} = vertsplit(@6) */
  w059 = w006[2];
  /* #328: @55 = (@55*@59) */
  w055 *= w059;
  /* #329: @59 = input[2][0] */
  w059 = arg[2] ? arg[2][0] : 0;
  /* #330: @60 = 100 */
  w060 = 100.;
  /* #331: @61 = input[1][0] */
  casadi_copy(arg[1], 5, w061);
  /* #332: @62 = @61[0] */
  for (rr=(&w062), cs=w061+0; cs!=w061+1; cs+=1) *rr++ = *cs;
  /* #333: @63 = 0 */
  w063 = 0.;
  /* #334: @64 = fmax(@62,@63) */
  w064  = casadi_fmax(w062,w063);
  /* #335: @65 = 100 */
  w065 = 100.;
  /* #336: @66 = fmin(@64,@65) */
  w066  = casadi_fmin(w064,w065);
  /* #337: @60 = (@60<@66) */
  w060  = (w060<w066);
  /* #338: @67 = 27 */
  w067 = 27.;
  /* #339: @67 = (@60?@67:0) */
  w067  = (w060?w067:0);
  /* #340: @60 = (!@60) */
  w060 = (! w060 );
  /* #341: @68 = 0 */
  w068 = 0.;
  /* #342: @68 = (@66<@68) */
  w068  = (w066<w068);
  /* #343: @68 = (!@68) */
  w068 = (! w068 );
  /* #344: @69 = 90 */
  w069 = 90.;
  /* #345: @69 = (@69<=@66) */
  w069  = (w069<=w066);
  /* #346: @70 = 100 */
  w070 = 100.;
  /* #347: @70 = (@66<=@70) */
  w070  = (w066<=w070);
  /* #348: @69 = (@69&&@70) */
  w069  = (w069&&w070);
  /* #349: @70 = 26.753 */
  w070 = 2.6752962991109627e+01;
  /* #350: @71 = 0.0247037 */
  w071 = 2.4703700889037349e-02;
  /* #351: @72 = 90 */
  w072 = 90.;
  /* #352: @72 = (@66-@72) */
  w072  = (w066-w072);
  /* #353: @72 = (@71*@72) */
  w072  = (w071*w072);
  /* #354: @70 = (@70+@72) */
  w070 += w072;
  /* #355: @70 = (@69?@70:0) */
  w070  = (w069?w070:0);
  /* #356: @72 = (!@69) */
  w072 = (! w069 );
  /* #357: @73 = 85 */
  w073 = 85.;
  /* #358: @73 = (@73<=@66) */
  w073  = (w073<=w066);
  /* #359: @74 = 90 */
  w074 = 90.;
  /* #360: @74 = (@66<=@74) */
  w074  = (w066<=w074);
  /* #361: @73 = (@73&&@74) */
  w073  = (w073&&w074);
  /* #362: @74 = 24.7588 */
  w074 = 2.4758844578012344e+01;
  /* #363: @75 = 0.398824 */
  w075 = 3.9882368261945655e-01;
  /* #364: @76 = 85 */
  w076 = 85.;
  /* #365: @76 = (@66-@76) */
  w076  = (w066-w076);
  /* #366: @76 = (@75*@76) */
  w076  = (w075*w076);
  /* #367: @74 = (@74+@76) */
  w074 += w076;
  /* #368: @74 = (@73?@74:0) */
  w074  = (w073?w074:0);
  /* #369: @76 = (!@73) */
  w076 = (! w073 );
  /* #370: @77 = 80 */
  w077 = 80.;
  /* #371: @77 = (@77<=@66) */
  w077  = (w077<=w066);
  /* #372: @78 = 85 */
  w078 = 85.;
  /* #373: @78 = (@66<=@78) */
  w078  = (w066<=w078);
  /* #374: @77 = (@77&&@78) */
  w077  = (w077&&w078);
  /* #375: @78 = 22.8389 */
  w078 = 2.2838908040823828e+01;
  /* #376: @79 = 0.383987 */
  w079 = 3.8398730743770315e-01;
  /* #377: @80 = 80 */
  w080 = 80.;
  /* #378: @80 = (@66-@80) */
  w080  = (w066-w080);
  /* #379: @80 = (@79*@80) */
  w080  = (w079*w080);
  /* #380: @78 = (@78+@80) */
  w078 += w080;
  /* #381: @78 = (@77?@78:0) */
  w078  = (w077?w078:0);
  /* #382: @80 = (!@77) */
  w080 = (! w077 );
  /* #383: @81 = 75 */
  w081 = 75.;
  /* #384: @81 = (@81<=@66) */
  w081  = (w081<=w066);
  /* #385: @82 = 80 */
  w082 = 80.;
  /* #386: @82 = (@66<=@82) */
  w082  = (w066<=w082);
  /* #387: @81 = (@81&&@82) */
  w081  = (w081&&w082);
  /* #388: @82 = 20.8242 */
  w082 = 2.0824175499723022e+01;
  /* #389: @83 = 0.402947 */
  w083 = 4.0294650822016109e-01;
  /* #390: @84 = 75 */
  w084 = 75.;
  /* #391: @84 = (@66-@84) */
  w084  = (w066-w084);
  /* #392: @84 = (@83*@84) */
  w084  = (w083*w084);
  /* #393: @82 = (@82+@84) */
  w082 += w084;
  /* #394: @82 = (@81?@82:0) */
  w082  = (w081?w082:0);
  /* #395: @84 = (!@81) */
  w084 = (! w081 );
  /* #396: @85 = 70 */
  w085 = 70.;
  /* #397: @85 = (@85<=@66) */
  w085  = (w085<=w066);
  /* #398: @86 = 75 */
  w086 = 75.;
  /* #399: @86 = (@66<=@86) */
  w086  = (w066<=w086);
  /* #400: @85 = (@85&&@86) */
  w085  = (w085&&w086);
  /* #401: @86 = 18.3959 */
  w086 = 1.8395945471821904e+01;
  /* #402: @87 = 0.485646 */
  w087 = 4.8564600558022375e-01;
  /* #403: @88 = 70 */
  w088 = 70.;
  /* #404: @88 = (@66-@88) */
  w088  = (w066-w088);
  /* #405: @88 = (@87*@88) */
  w088  = (w087*w088);
  /* #406: @86 = (@86+@88) */
  w086 += w088;
  /* #407: @86 = (@85?@86:0) */
  w086  = (w085?w086:0);
  /* #408: @88 = (!@85) */
  w088 = (! w085 );
  /* #409: @89 = 60 */
  w089 = 60.;
  /* #410: @89 = (@89<=@66) */
  w089  = (w089<=w066);
  /* #411: @90 = 70 */
  w090 = 70.;
  /* #412: @90 = (@66<=@90) */
  w090  = (w066<=w090);
  /* #413: @89 = (@89&&@90) */
  w089  = (w089&&w090);
  /* #414: @90 = 14.7408 */
  w090 = 1.4740834272959603e+01;
  /* #415: @91 = 0.365511 */
  w091 = 3.6551111988623008e-01;
  /* #416: @92 = 60 */
  w092 = 60.;
  /* #417: @92 = (@66-@92) */
  w092  = (w066-w092);
  /* #418: @92 = (@91*@92) */
  w092  = (w091*w092);
  /* #419: @90 = (@90+@92) */
  w090 += w092;
  /* #420: @90 = (@89?@90:0) */
  w090  = (w089?w090:0);
  /* #421: @92 = (!@89) */
  w092 = (! w089 );
  /* #422: @93 = 50 */
  w093 = 50.;
  /* #423: @93 = (@93<=@66) */
  w093  = (w093<=w066);
  /* #424: @94 = 60 */
  w094 = 60.;
  /* #425: @94 = (@66<=@94) */
  w094  = (w066<=w094);
  /* #426: @93 = (@93&&@94) */
  w093  = (w093&&w094);
  /* #427: @94 = 12.0425 */
  w094 = 1.2042451609558308e+01;
  /* #428: @95 = 0.269838 */
  w095 = 2.6983826634012953e-01;
  /* #429: @96 = 50 */
  w096 = 50.;
  /* #430: @96 = (@66-@96) */
  w096  = (w066-w096);
  /* #431: @96 = (@95*@96) */
  w096  = (w095*w096);
  /* #432: @94 = (@94+@96) */
  w094 += w096;
  /* #433: @94 = (@93?@94:0) */
  w094  = (w093?w094:0);
  /* #434: @96 = (!@93) */
  w096 = (! w093 );
  /* #435: @97 = 40 */
  w097 = 40.;
  /* #436: @97 = (@97<=@66) */
  w097  = (w097<=w066);
  /* #437: @98 = 50 */
  w098 = 50.;
  /* #438: @98 = (@66<=@98) */
  w098  = (w066<=w098);
  /* #439: @97 = (@97&&@98) */
  w097  = (w097&&w098);
  /* #440: @98 = 9.61328 */
  w098 = 9.6132801575173321e+00;
  /* #441: @99 = 0.242917 */
  w099 = 2.4291714520409755e-01;
  /* #442: @100 = 40 */
  w100 = 40.;
  /* #443: @100 = (@66-@100) */
  w100  = (w066-w100);
  /* #444: @100 = (@99*@100) */
  w100  = (w099*w100);
  /* #445: @98 = (@98+@100) */
  w098 += w100;
  /* #446: @98 = (@97?@98:0) */
  w098  = (w097?w098:0);
  /* #447: @100 = (!@97) */
  w100 = (! w097 );
  /* #448: @101 = 30 */
  w101 = 30.;
  /* #449: @101 = (@101<=@66) */
  w101  = (w101<=w066);
  /* #450: @102 = 40 */
  w102 = 40.;
  /* #451: @102 = (@66<=@102) */
  w102  = (w066<=w102);
  /* #452: @101 = (@101&&@102) */
  w101  = (w101&&w102);
  /* #453: @102 = 7.04574 */
  w102 = 7.0457390494971124e+00;
  /* #454: @103 = 0.256754 */
  w103 = 2.5675411080202198e-01;
  /* #455: @104 = 30 */
  w104 = 30.;
  /* #456: @104 = (@66-@104) */
  w104  = (w066-w104);
  /* #457: @104 = (@103*@104) */
  w104  = (w103*w104);
  /* #458: @102 = (@102+@104) */
  w102 += w104;
  /* #459: @102 = (@101?@102:0) */
  w102  = (w101?w102:0);
  /* #460: @104 = (!@101) */
  w104 = (! w101 );
  /* #461: @105 = 20 */
  w105 = 20.;
  /* #462: @105 = (@105<=@66) */
  w105  = (w105<=w066);
  /* #463: @106 = 30 */
  w106 = 30.;
  /* #464: @106 = (@66<=@106) */
  w106  = (w066<=w106);
  /* #465: @105 = (@105&&@106) */
  w105  = (w105&&w106);
  /* #466: @106 = 4.24854 */
  w106 = 4.2485368817013320e+00;
  /* #467: @107 = 0.27972 */
  w107 = 2.7972021677957803e-01;
  /* #468: @108 = 20 */
  w108 = 20.;
  /* #469: @108 = (@66-@108) */
  w108  = (w066-w108);
  /* #470: @108 = (@107*@108) */
  w108  = (w107*w108);
  /* #471: @106 = (@106+@108) */
  w106 += w108;
  /* #472: @106 = (@105?@106:0) */
  w106  = (w105?w106:0);
  /* #473: @108 = (!@105) */
  w108 = (! w105 );
  /* #474: @109 = 10 */
  w109 = 10.;
  /* #475: @109 = (@109<=@66) */
  w109  = (w109<=w066);
  /* #476: @110 = 20 */
  w110 = 20.;
  /* #477: @110 = (@66<=@110) */
  w110  = (w066<=w110);
  /* #478: @109 = (@109&&@110) */
  w109  = (w109&&w110);
  /* #479: @110 = 1.46239 */
  w110 = 1.4623894660200982e+00;
  /* #480: @111 = 0.278615 */
  w111 = 2.7861474156812338e-01;
  /* #481: @112 = 10 */
  w112 = 10.;
  /* #482: @112 = (@66-@112) */
  w112  = (w066-w112);
  /* #483: @112 = (@111*@112) */
  w112  = (w111*w112);
  /* #484: @110 = (@110+@112) */
  w110 += w112;
  /* #485: @110 = (@109?@110:0) */
  w110  = (w109?w110:0);
  /* #486: @112 = (!@109) */
  w112 = (! w109 );
  /* #487: @113 = 0 */
  w113 = 0.;
  /* #488: @113 = (@113<=@66) */
  w113  = (w113<=w066);
  /* #489: @114 = 10 */
  w114 = 10.;
  /* #490: @114 = (@66<=@114) */
  w114  = (w066<=w114);
  /* #491: @113 = (@113&&@114) */
  w113  = (w113&&w114);
  /* #492: @114 = 0.146239 */
  w114 = 1.4623894660200981e-01;
  /* #493: @66 = (@114*@66) */
  w066  = (w114*w066);
  /* #494: @66 = (@113?@66:0) */
  w066  = (w113?w066:0);
  /* #495: @66 = (@112?@66:0) */
  w066  = (w112?w066:0);
  /* #496: @110 = (@110+@66) */
  w110 += w066;
  /* #497: @110 = (@108?@110:0) */
  w110  = (w108?w110:0);
  /* #498: @106 = (@106+@110) */
  w106 += w110;
  /* #499: @106 = (@104?@106:0) */
  w106  = (w104?w106:0);
  /* #500: @102 = (@102+@106) */
  w102 += w106;
  /* #501: @102 = (@100?@102:0) */
  w102  = (w100?w102:0);
  /* #502: @98 = (@98+@102) */
  w098 += w102;
  /* #503: @98 = (@96?@98:0) */
  w098  = (w096?w098:0);
  /* #504: @94 = (@94+@98) */
  w094 += w098;
  /* #505: @94 = (@92?@94:0) */
  w094  = (w092?w094:0);
  /* #506: @90 = (@90+@94) */
  w090 += w094;
  /* #507: @90 = (@88?@90:0) */
  w090  = (w088?w090:0);
  /* #508: @86 = (@86+@90) */
  w086 += w090;
  /* #509: @86 = (@84?@86:0) */
  w086  = (w084?w086:0);
  /* #510: @82 = (@82+@86) */
  w082 += w086;
  /* #511: @82 = (@80?@82:0) */
  w082  = (w080?w082:0);
  /* #512: @78 = (@78+@82) */
  w078 += w082;
  /* #513: @78 = (@76?@78:0) */
  w078  = (w076?w078:0);
  /* #514: @74 = (@74+@78) */
  w074 += w078;
  /* #515: @74 = (@72?@74:0) */
  w074  = (w072?w074:0);
  /* #516: @70 = (@70+@74) */
  w070 += w074;
  /* #517: @70 = (@68?@70:0) */
  w070  = (w068?w070:0);
  /* #518: @70 = (@60?@70:0) */
  w070  = (w060?w070:0);
  /* #519: @67 = (@67+@70) */
  w067 += w070;
  /* #520: @70 = (@59*@67) */
  w070  = (w059*w067);
  /* #521: @70 = (@16<@70) */
  w070  = (w016<w070);
  /* #522: @74 = 0.18 */
  w074 = 1.7999999999999999e-01;
  /* #523: @74 = (@70?@74:0) */
  w074  = (w070?w074:0);
  /* #524: @70 = (!@70) */
  w070 = (! w070 );
  /* #525: @78 = 0.22 */
  w078 = 2.2000000000000000e-01;
  /* #526: @70 = (@70?@78:0) */
  w070  = (w070?w078:0);
  /* #527: @74 = (@74+@70) */
  w074 += w070;
  /* #528: @7 = (@7/@74) */
  w007 /= w074;
  /* #529: @55 = (@55-@7) */
  w055 -= w007;
  /* #530: @20 = sin(@20) */
  w020 = sin( w020 );
  /* #531: @20 = (@20*@26) */
  w020 *= w026;
  /* #532: @18 = (@18*@20) */
  w018 *= w020;
  /* #533: @55 = (@55+@18) */
  w055 += w018;
  /* #534: @19 = sin(@19) */
  w019 = sin( w019 );
  /* #535: @19 = (@19*@29) */
  w019 *= w029;
  /* #536: @25 = (@25*@19) */
  w025 *= w019;
  /* #537: @55 = (@55+@25) */
  w055 += w025;
  /* #538: @22 = sin(@22) */
  w022 = sin( w022 );
  /* #539: @22 = (@22*@32) */
  w022 *= w032;
  /* #540: @28 = (@28*@22) */
  w028 *= w022;
  /* #541: @55 = (@55+@28) */
  w055 += w028;
  /* #542: @23 = sin(@23) */
  w023 = sin( w023 );
  /* #543: @23 = (@23*@35) */
  w023 *= w035;
  /* #544: @31 = (@31*@23) */
  w031 *= w023;
  /* #545: @55 = (@55+@31) */
  w055 += w031;
  /* #546: @30 = sin(@30) */
  w030 = sin( w030 );
  /* #547: @21 = (@30*@21) */
  w021  = (w030*w021);
  /* #548: @34 = (@34*@21) */
  w034 *= w021;
  /* #549: @55 = (@55+@34) */
  w055 += w034;
  /* #550: @27 = sin(@27) */
  w027 = sin( w027 );
  /* #551: @49 = (@27*@49) */
  w049  = (w027*w049);
  /* #552: @46 = (@46*@49) */
  w046 *= w049;
  /* #553: @55 = (@55+@46) */
  w055 += w046;
  /* #554: @33 = sin(@33) */
  w033 = sin( w033 );
  /* #555: @54 = (@33*@54) */
  w054  = (w033*w054);
  /* #556: @52 = (@52*@54) */
  w052 *= w054;
  /* #557: @55 = (@55+@52) */
  w055 += w052;
  /* #558: @51 = sin(@51) */
  w051 = sin( w051 );
  /* #559: @58 = (@51*@58) */
  w058  = (w051*w058);
  /* #560: @56 = (@56*@58) */
  w056 *= w058;
  /* #561: @55 = (@55+@56) */
  w055 += w056;
  /* #562: {NULL, NULL, @56} = vertsplit(@14) */
  w056 = w014[2];
  /* #563: @55 = (@55+@56) */
  w055 += w056;
  /* #564: (@0[13] += @55) */
  for (rr=w000+13, cs=(&w055); rr!=w000+14; rr+=1) *rr += *cs++;
  /* #565: @15 = zeros(3x3) */
  casadi_clear(w015, 9);
  /* #566: @55 = 0 */
  w055 = 0.;
  /* #567: @56 = 0 */
  w056 = 0.;
  /* #568: @14 = vertcat(@55, @56, @16) */
  rr=w014;
  *rr++ = w055;
  *rr++ = w056;
  *rr++ = w016;
  /* #569: @57 = (@57*@51) */
  w057 *= w051;
  /* #570: @50 = (@50*@57) */
  for (i=0, rr=w050; i<3; ++i) (*rr++) *= w057;
  /* #571: @53 = (@53*@33) */
  w053 *= w033;
  /* #572: @48 = (@48*@53) */
  for (i=0, rr=w048; i<3; ++i) (*rr++) *= w053;
  /* #573: @50 = (@50+@48) */
  for (i=0, rr=w050, cs=w048; i<3; ++i) (*rr++) += (*cs++);
  /* #574: @47 = (@47*@27) */
  w047 *= w027;
  /* #575: @24 = (@24*@47) */
  for (i=0, rr=w024; i<3; ++i) (*rr++) *= w047;
  /* #576: @50 = (@50+@24) */
  for (i=0, rr=w050, cs=w024; i<3; ++i) (*rr++) += (*cs++);
  /* #577: @17 = (@17*@30) */
  w017 *= w030;
  /* #578: @12 = (@12*@17) */
  for (i=0, rr=w012; i<3; ++i) (*rr++) *= w017;
  /* #579: @50 = (@50+@12) */
  for (i=0, rr=w050, cs=w012; i<3; ++i) (*rr++) += (*cs++);
  /* #580: @14 = (@14+@50) */
  for (i=0, rr=w014, cs=w050; i<3; ++i) (*rr++) += (*cs++);
  /* #581: @14 = @14' */
  /* #582: @15 = mac(@4,@14,@15) */
  for (i=0, rr=w015; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w004+j, ct=w014+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #583: @13 = @15' */
  for (i=0, rr=w013, cs=w015; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #584: {@4, @14, @50} = horzsplit(@13) */
  casadi_copy(w013, 3, w004);
  casadi_copy(w013+3, 3, w014);
  casadi_copy(w013+6, 3, w050);
  /* #585: @50 = @50' */
  /* #586: {@17, @30, @47} = horzsplit(@50) */
  w017 = w050[0];
  w030 = w050[1];
  w047 = w050[2];
  /* #587: @30 = (2.*@30) */
  w030 = (2.* w030 );
  /* #588: @27 = (@36*@30) */
  w027  = (w036*w030);
  /* #589: @17 = (2.*@17) */
  w017 = (2.* w017 );
  /* #590: @53 = (@44*@17) */
  w053  = (w044*w017);
  /* #591: @27 = (@27-@53) */
  w027 -= w053;
  /* #592: @14 = @14' */
  /* #593: {@53, @33, @57} = horzsplit(@14) */
  w053 = w014[0];
  w033 = w014[1];
  w057 = w014[2];
  /* #594: @57 = (2.*@57) */
  w057 = (2.* w057 );
  /* #595: @51 = (@36*@57) */
  w051  = (w036*w057);
  /* #596: @27 = (@27-@51) */
  w027 -= w051;
  /* #597: @53 = (2.*@53) */
  w053 = (2.* w053 );
  /* #598: @51 = (@8*@53) */
  w051  = (w008*w053);
  /* #599: @27 = (@27+@51) */
  w027 += w051;
  /* #600: @4 = @4' */
  /* #601: {@51, @55, @56} = horzsplit(@4) */
  w051 = w004[0];
  w055 = w004[1];
  w056 = w004[2];
  /* #602: @56 = (2.*@56) */
  w056 = (2.* w056 );
  /* #603: @16 = (@44*@56) */
  w016  = (w044*w056);
  /* #604: @27 = (@27+@16) */
  w027 += w016;
  /* #605: @55 = (2.*@55) */
  w055 = (2.* w055 );
  /* #606: @16 = (@8*@55) */
  w016  = (w008*w055);
  /* #607: @27 = (@27-@16) */
  w027 -= w016;
  /* #608: (@0[6] += @27) */
  for (rr=w000+6, cs=(&w027); rr!=w000+7; rr+=1) *rr += *cs++;
  /* #609: @27 = (2.*@36) */
  w027 = (2.* w036 );
  /* #610: @47 = (-@47) */
  w047 = (- w047 );
  /* #611: @47 = (2.*@47) */
  w047 = (2.* w047 );
  /* #612: @27 = (@27*@47) */
  w027 *= w047;
  /* #613: @16 = (@45*@30) */
  w016  = (w045*w030);
  /* #614: @27 = (@27+@16) */
  w027 += w016;
  /* #615: @16 = (@8*@17) */
  w016  = (w008*w017);
  /* #616: @27 = (@27+@16) */
  w027 += w016;
  /* #617: @16 = (@45*@57) */
  w016  = (w045*w057);
  /* #618: @27 = (@27-@16) */
  w027 -= w016;
  /* #619: @16 = (2.*@36) */
  w016 = (2.* w036 );
  /* #620: @33 = (-@33) */
  w033 = (- w033 );
  /* #621: @33 = (2.*@33) */
  w033 = (2.* w033 );
  /* #622: @16 = (@16*@33) */
  w016 *= w033;
  /* #623: @27 = (@27+@16) */
  w027 += w016;
  /* #624: @16 = (@44*@53) */
  w016  = (w044*w053);
  /* #625: @27 = (@27+@16) */
  w027 += w016;
  /* #626: @16 = (@8*@56) */
  w016  = (w008*w056);
  /* #627: @27 = (@27+@16) */
  w027 += w016;
  /* #628: @16 = (@44*@55) */
  w016  = (w044*w055);
  /* #629: @27 = (@27+@16) */
  w027 += w016;
  /* #630: (@0[7] += @27) */
  for (rr=w000+7, cs=(&w027); rr!=w000+8; rr+=1) *rr += *cs++;
  /* #631: @27 = (@44*@30) */
  w027  = (w044*w030);
  /* #632: @16 = (@36*@17) */
  w016  = (w036*w017);
  /* #633: @27 = (@27+@16) */
  w027 += w016;
  /* #634: @16 = (@44*@57) */
  w016  = (w044*w057);
  /* #635: @27 = (@27+@16) */
  w027 += w016;
  /* #636: @16 = (2.*@8) */
  w016 = (2.* w008 );
  /* #637: @16 = (@16*@33) */
  w016 *= w033;
  /* #638: @27 = (@27+@16) */
  w027 += w016;
  /* #639: @16 = (@45*@53) */
  w016  = (w045*w053);
  /* #640: @27 = (@27+@16) */
  w027 += w016;
  /* #641: @16 = (@36*@56) */
  w016  = (w036*w056);
  /* #642: @27 = (@27+@16) */
  w027 += w016;
  /* #643: @16 = (@45*@55) */
  w016  = (w045*w055);
  /* #644: @27 = (@27-@16) */
  w027 -= w016;
  /* #645: @16 = (2.*@8) */
  w016 = (2.* w008 );
  /* #646: @51 = (-@51) */
  w051 = (- w051 );
  /* #647: @51 = (2.*@51) */
  w051 = (2.* w051 );
  /* #648: @16 = (@16*@51) */
  w016 *= w051;
  /* #649: @27 = (@27+@16) */
  w027 += w016;
  /* #650: (@0[9] += @27) */
  for (rr=w000+9, cs=(&w027); rr!=w000+10; rr+=1) *rr += *cs++;
  /* #651: @27 = (2.*@44) */
  w027 = (2.* w044 );
  /* #652: @27 = (@27*@47) */
  w027 *= w047;
  /* #653: @30 = (@8*@30) */
  w030  = (w008*w030);
  /* #654: @27 = (@27+@30) */
  w027 += w030;
  /* #655: @17 = (@45*@17) */
  w017  = (w045*w017);
  /* #656: @27 = (@27-@17) */
  w027 -= w017;
  /* #657: @8 = (@8*@57) */
  w008 *= w057;
  /* #658: @27 = (@27+@8) */
  w027 += w008;
  /* #659: @53 = (@36*@53) */
  w053  = (w036*w053);
  /* #660: @27 = (@27+@53) */
  w027 += w053;
  /* #661: @45 = (@45*@56) */
  w045 *= w056;
  /* #662: @27 = (@27+@45) */
  w027 += w045;
  /* #663: @36 = (@36*@55) */
  w036 *= w055;
  /* #664: @27 = (@27+@36) */
  w027 += w036;
  /* #665: @44 = (2.*@44) */
  w044 = (2.* w044 );
  /* #666: @44 = (@44*@51) */
  w044 *= w051;
  /* #667: @27 = (@27+@44) */
  w027 += w044;
  /* #668: (@0[8] += @27) */
  for (rr=w000+8, cs=(&w027); rr!=w000+9; rr+=1) *rr += *cs++;
  /* #669: (@0[3:6] += @3) */
  for (rr=w000+3, cs=wr003; rr!=w000+6; rr+=1) *rr += *cs++;
  /* #670: output[0][0] = @0 */
  casadi_copy(w000, 18, res[0]);
  /* #671: @115 = zeros(5x1) */
  casadi_clear(w115, 5);
  /* #672: @27 = -34 */
  w027 = -34.;
  /* #673: @44 = @61[4] */
  for (rr=(&w044), cs=w061+4; cs!=w061+5; cs+=1) *rr++ = *cs;
  /* #674: @51 = (@27<=@44) */
  w051  = (w027<=w044);
  /* #675: @36 = (@44<=@27) */
  w036  = (w044<=w027);
  /* #676: @36 = (@51+@36) */
  w036  = (w051+w036);
  /* #677: @51 = (@51/@36) */
  w051 /= w036;
  /* #678: @44 = fmax(@44,@27) */
  w044  = casadi_fmax(w044,w027);
  /* #679: @27 = 34 */
  w027 = 34.;
  /* #680: @36 = (@44<=@27) */
  w036  = (w044<=w027);
  /* #681: @27 = (@27<=@44) */
  w027  = (w027<=w044);
  /* #682: @27 = (@36+@27) */
  w027  = (w036+w027);
  /* #683: @36 = (@36/@27) */
  w036 /= w027;
  /* #684: @27 = 3.14159 */
  w027 = 3.1415926535897931e+00;
  /* #685: @44 = 0.00555556 */
  w044 = 5.5555555555555558e-03;
  /* #686: @44 = (@44*@1) */
  w044 *= w001;
  /* #687: @27 = (@27*@44) */
  w027 *= w044;
  /* #688: @36 = (@36*@27) */
  w036 *= w027;
  /* #689: @51 = (@51*@36) */
  w051 *= w036;
  /* #690: (@115[4] += @51) */
  for (rr=w115+4, cs=(&w051); rr!=w115+5; rr+=1) *rr += *cs++;
  /* #691: @51 = -34 */
  w051 = -34.;
  /* #692: @36 = @61[3] */
  for (rr=(&w036), cs=w061+3; cs!=w061+4; cs+=1) *rr++ = *cs;
  /* #693: @27 = (@51<=@36) */
  w027  = (w051<=w036);
  /* #694: @44 = (@36<=@51) */
  w044  = (w036<=w051);
  /* #695: @44 = (@27+@44) */
  w044  = (w027+w044);
  /* #696: @27 = (@27/@44) */
  w027 /= w044;
  /* #697: @36 = fmax(@36,@51) */
  w036  = casadi_fmax(w036,w051);
  /* #698: @51 = 34 */
  w051 = 34.;
  /* #699: @44 = (@36<=@51) */
  w044  = (w036<=w051);
  /* #700: @51 = (@51<=@36) */
  w051  = (w051<=w036);
  /* #701: @51 = (@44+@51) */
  w051  = (w044+w051);
  /* #702: @44 = (@44/@51) */
  w044 /= w051;
  /* #703: @51 = 3.14159 */
  w051 = 3.1415926535897931e+00;
  /* #704: @36 = 0.00555556 */
  w036 = 5.5555555555555558e-03;
  /* #705: @36 = (@36*@11) */
  w036 *= w011;
  /* #706: @51 = (@51*@36) */
  w051 *= w036;
  /* #707: @44 = (@44*@51) */
  w044 *= w051;
  /* #708: @27 = (@27*@44) */
  w027 *= w044;
  /* #709: (@115[3] += @27) */
  for (rr=w115+3, cs=(&w027); rr!=w115+4; rr+=1) *rr += *cs++;
  /* #710: @27 = -34 */
  w027 = -34.;
  /* #711: @44 = @61[2] */
  for (rr=(&w044), cs=w061+2; cs!=w061+3; cs+=1) *rr++ = *cs;
  /* #712: @51 = (@27<=@44) */
  w051  = (w027<=w044);
  /* #713: @36 = (@44<=@27) */
  w036  = (w044<=w027);
  /* #714: @36 = (@51+@36) */
  w036  = (w051+w036);
  /* #715: @51 = (@51/@36) */
  w051 /= w036;
  /* #716: @44 = fmax(@44,@27) */
  w044  = casadi_fmax(w044,w027);
  /* #717: @27 = 34 */
  w027 = 34.;
  /* #718: @36 = (@44<=@27) */
  w036  = (w044<=w027);
  /* #719: @27 = (@27<=@44) */
  w027  = (w027<=w044);
  /* #720: @27 = (@36+@27) */
  w027  = (w036+w027);
  /* #721: @36 = (@36/@27) */
  w036 /= w027;
  /* #722: @27 = 3.14159 */
  w027 = 3.1415926535897931e+00;
  /* #723: @44 = 0.00555556 */
  w044 = 5.5555555555555558e-03;
  /* #724: @44 = (@44*@10) */
  w044 *= w010;
  /* #725: @27 = (@27*@44) */
  w027 *= w044;
  /* #726: @36 = (@36*@27) */
  w036 *= w027;
  /* #727: @51 = (@51*@36) */
  w051 *= w036;
  /* #728: (@115[2] += @51) */
  for (rr=w115+2, cs=(&w051); rr!=w115+3; rr+=1) *rr += *cs++;
  /* #729: @51 = -34 */
  w051 = -34.;
  /* #730: @36 = @61[1] */
  for (rr=(&w036), cs=w061+1; cs!=w061+2; cs+=1) *rr++ = *cs;
  /* #731: @27 = (@51<=@36) */
  w027  = (w051<=w036);
  /* #732: @44 = (@36<=@51) */
  w044  = (w036<=w051);
  /* #733: @44 = (@27+@44) */
  w044  = (w027+w044);
  /* #734: @27 = (@27/@44) */
  w027 /= w044;
  /* #735: @36 = fmax(@36,@51) */
  w036  = casadi_fmax(w036,w051);
  /* #736: @51 = 34 */
  w051 = 34.;
  /* #737: @44 = (@36<=@51) */
  w044  = (w036<=w051);
  /* #738: @51 = (@51<=@36) */
  w051  = (w051<=w036);
  /* #739: @51 = (@44+@51) */
  w051  = (w044+w051);
  /* #740: @44 = (@44/@51) */
  w044 /= w051;
  /* #741: @51 = 3.14159 */
  w051 = 3.1415926535897931e+00;
  /* #742: @36 = 0.00555556 */
  w036 = 5.5555555555555558e-03;
  /* #743: @36 = (@36*@9) */
  w036 *= w009;
  /* #744: @51 = (@51*@36) */
  w051 *= w036;
  /* #745: @44 = (@44*@51) */
  w044 *= w051;
  /* #746: @27 = (@27*@44) */
  w027 *= w044;
  /* #747: (@115[1] += @27) */
  for (rr=w115+1, cs=(&w027); rr!=w115+2; rr+=1) *rr += *cs++;
  /* #748: @27 = (@63<=@62) */
  w027  = (w063<=w062);
  /* #749: @62 = (@62<=@63) */
  w062  = (w062<=w063);
  /* #750: @62 = (@27+@62) */
  w062  = (w027+w062);
  /* #751: @27 = (@27/@62) */
  w027 /= w062;
  /* #752: @62 = (@64<=@65) */
  w062  = (w064<=w065);
  /* #753: @65 = (@65<=@64) */
  w065  = (w065<=w064);
  /* #754: @65 = (@62+@65) */
  w065  = (w062+w065);
  /* #755: @62 = (@62/@65) */
  w062 /= w065;
  /* #756: @59 = (@59*@7) */
  w059 *= w007;
  /* #757: @114 = (@114*@59) */
  w114 *= w059;
  /* #758: @114 = (@60?@114:0) */
  w114  = (w060?w114:0);
  /* #759: @114 = (@68?@114:0) */
  w114  = (w068?w114:0);
  /* #760: @114 = (@72?@114:0) */
  w114  = (w072?w114:0);
  /* #761: @114 = (@76?@114:0) */
  w114  = (w076?w114:0);
  /* #762: @114 = (@80?@114:0) */
  w114  = (w080?w114:0);
  /* #763: @114 = (@84?@114:0) */
  w114  = (w084?w114:0);
  /* #764: @114 = (@88?@114:0) */
  w114  = (w088?w114:0);
  /* #765: @114 = (@92?@114:0) */
  w114  = (w092?w114:0);
  /* #766: @114 = (@96?@114:0) */
  w114  = (w096?w114:0);
  /* #767: @114 = (@100?@114:0) */
  w114  = (w100?w114:0);
  /* #768: @114 = (@104?@114:0) */
  w114  = (w104?w114:0);
  /* #769: @114 = (@108?@114:0) */
  w114  = (w108?w114:0);
  /* #770: @112 = (@112?@114:0) */
  w112  = (w112?w114:0);
  /* #771: @113 = (@113?@112:0) */
  w113  = (w113?w112:0);
  /* #772: @111 = (@111*@59) */
  w111 *= w059;
  /* #773: @111 = (@60?@111:0) */
  w111  = (w060?w111:0);
  /* #774: @111 = (@68?@111:0) */
  w111  = (w068?w111:0);
  /* #775: @111 = (@72?@111:0) */
  w111  = (w072?w111:0);
  /* #776: @111 = (@76?@111:0) */
  w111  = (w076?w111:0);
  /* #777: @111 = (@80?@111:0) */
  w111  = (w080?w111:0);
  /* #778: @111 = (@84?@111:0) */
  w111  = (w084?w111:0);
  /* #779: @111 = (@88?@111:0) */
  w111  = (w088?w111:0);
  /* #780: @111 = (@92?@111:0) */
  w111  = (w092?w111:0);
  /* #781: @111 = (@96?@111:0) */
  w111  = (w096?w111:0);
  /* #782: @111 = (@100?@111:0) */
  w111  = (w100?w111:0);
  /* #783: @111 = (@104?@111:0) */
  w111  = (w104?w111:0);
  /* #784: @108 = (@108?@111:0) */
  w108  = (w108?w111:0);
  /* #785: @109 = (@109?@108:0) */
  w109  = (w109?w108:0);
  /* #786: @113 = (@113+@109) */
  w113 += w109;
  /* #787: @107 = (@107*@59) */
  w107 *= w059;
  /* #788: @107 = (@60?@107:0) */
  w107  = (w060?w107:0);
  /* #789: @107 = (@68?@107:0) */
  w107  = (w068?w107:0);
  /* #790: @107 = (@72?@107:0) */
  w107  = (w072?w107:0);
  /* #791: @107 = (@76?@107:0) */
  w107  = (w076?w107:0);
  /* #792: @107 = (@80?@107:0) */
  w107  = (w080?w107:0);
  /* #793: @107 = (@84?@107:0) */
  w107  = (w084?w107:0);
  /* #794: @107 = (@88?@107:0) */
  w107  = (w088?w107:0);
  /* #795: @107 = (@92?@107:0) */
  w107  = (w092?w107:0);
  /* #796: @107 = (@96?@107:0) */
  w107  = (w096?w107:0);
  /* #797: @107 = (@100?@107:0) */
  w107  = (w100?w107:0);
  /* #798: @104 = (@104?@107:0) */
  w104  = (w104?w107:0);
  /* #799: @105 = (@105?@104:0) */
  w105  = (w105?w104:0);
  /* #800: @113 = (@113+@105) */
  w113 += w105;
  /* #801: @103 = (@103*@59) */
  w103 *= w059;
  /* #802: @103 = (@60?@103:0) */
  w103  = (w060?w103:0);
  /* #803: @103 = (@68?@103:0) */
  w103  = (w068?w103:0);
  /* #804: @103 = (@72?@103:0) */
  w103  = (w072?w103:0);
  /* #805: @103 = (@76?@103:0) */
  w103  = (w076?w103:0);
  /* #806: @103 = (@80?@103:0) */
  w103  = (w080?w103:0);
  /* #807: @103 = (@84?@103:0) */
  w103  = (w084?w103:0);
  /* #808: @103 = (@88?@103:0) */
  w103  = (w088?w103:0);
  /* #809: @103 = (@92?@103:0) */
  w103  = (w092?w103:0);
  /* #810: @103 = (@96?@103:0) */
  w103  = (w096?w103:0);
  /* #811: @100 = (@100?@103:0) */
  w100  = (w100?w103:0);
  /* #812: @101 = (@101?@100:0) */
  w101  = (w101?w100:0);
  /* #813: @113 = (@113+@101) */
  w113 += w101;
  /* #814: @99 = (@99*@59) */
  w099 *= w059;
  /* #815: @99 = (@60?@99:0) */
  w099  = (w060?w099:0);
  /* #816: @99 = (@68?@99:0) */
  w099  = (w068?w099:0);
  /* #817: @99 = (@72?@99:0) */
  w099  = (w072?w099:0);
  /* #818: @99 = (@76?@99:0) */
  w099  = (w076?w099:0);
  /* #819: @99 = (@80?@99:0) */
  w099  = (w080?w099:0);
  /* #820: @99 = (@84?@99:0) */
  w099  = (w084?w099:0);
  /* #821: @99 = (@88?@99:0) */
  w099  = (w088?w099:0);
  /* #822: @99 = (@92?@99:0) */
  w099  = (w092?w099:0);
  /* #823: @96 = (@96?@99:0) */
  w096  = (w096?w099:0);
  /* #824: @97 = (@97?@96:0) */
  w097  = (w097?w096:0);
  /* #825: @113 = (@113+@97) */
  w113 += w097;
  /* #826: @95 = (@95*@59) */
  w095 *= w059;
  /* #827: @95 = (@60?@95:0) */
  w095  = (w060?w095:0);
  /* #828: @95 = (@68?@95:0) */
  w095  = (w068?w095:0);
  /* #829: @95 = (@72?@95:0) */
  w095  = (w072?w095:0);
  /* #830: @95 = (@76?@95:0) */
  w095  = (w076?w095:0);
  /* #831: @95 = (@80?@95:0) */
  w095  = (w080?w095:0);
  /* #832: @95 = (@84?@95:0) */
  w095  = (w084?w095:0);
  /* #833: @95 = (@88?@95:0) */
  w095  = (w088?w095:0);
  /* #834: @92 = (@92?@95:0) */
  w092  = (w092?w095:0);
  /* #835: @93 = (@93?@92:0) */
  w093  = (w093?w092:0);
  /* #836: @113 = (@113+@93) */
  w113 += w093;
  /* #837: @91 = (@91*@59) */
  w091 *= w059;
  /* #838: @91 = (@60?@91:0) */
  w091  = (w060?w091:0);
  /* #839: @91 = (@68?@91:0) */
  w091  = (w068?w091:0);
  /* #840: @91 = (@72?@91:0) */
  w091  = (w072?w091:0);
  /* #841: @91 = (@76?@91:0) */
  w091  = (w076?w091:0);
  /* #842: @91 = (@80?@91:0) */
  w091  = (w080?w091:0);
  /* #843: @91 = (@84?@91:0) */
  w091  = (w084?w091:0);
  /* #844: @88 = (@88?@91:0) */
  w088  = (w088?w091:0);
  /* #845: @89 = (@89?@88:0) */
  w089  = (w089?w088:0);
  /* #846: @113 = (@113+@89) */
  w113 += w089;
  /* #847: @87 = (@87*@59) */
  w087 *= w059;
  /* #848: @87 = (@60?@87:0) */
  w087  = (w060?w087:0);
  /* #849: @87 = (@68?@87:0) */
  w087  = (w068?w087:0);
  /* #850: @87 = (@72?@87:0) */
  w087  = (w072?w087:0);
  /* #851: @87 = (@76?@87:0) */
  w087  = (w076?w087:0);
  /* #852: @87 = (@80?@87:0) */
  w087  = (w080?w087:0);
  /* #853: @84 = (@84?@87:0) */
  w084  = (w084?w087:0);
  /* #854: @85 = (@85?@84:0) */
  w085  = (w085?w084:0);
  /* #855: @113 = (@113+@85) */
  w113 += w085;
  /* #856: @83 = (@83*@59) */
  w083 *= w059;
  /* #857: @83 = (@60?@83:0) */
  w083  = (w060?w083:0);
  /* #858: @83 = (@68?@83:0) */
  w083  = (w068?w083:0);
  /* #859: @83 = (@72?@83:0) */
  w083  = (w072?w083:0);
  /* #860: @83 = (@76?@83:0) */
  w083  = (w076?w083:0);
  /* #861: @80 = (@80?@83:0) */
  w080  = (w080?w083:0);
  /* #862: @81 = (@81?@80:0) */
  w081  = (w081?w080:0);
  /* #863: @113 = (@113+@81) */
  w113 += w081;
  /* #864: @79 = (@79*@59) */
  w079 *= w059;
  /* #865: @79 = (@60?@79:0) */
  w079  = (w060?w079:0);
  /* #866: @79 = (@68?@79:0) */
  w079  = (w068?w079:0);
  /* #867: @79 = (@72?@79:0) */
  w079  = (w072?w079:0);
  /* #868: @76 = (@76?@79:0) */
  w076  = (w076?w079:0);
  /* #869: @77 = (@77?@76:0) */
  w077  = (w077?w076:0);
  /* #870: @113 = (@113+@77) */
  w113 += w077;
  /* #871: @75 = (@75*@59) */
  w075 *= w059;
  /* #872: @75 = (@60?@75:0) */
  w075  = (w060?w075:0);
  /* #873: @75 = (@68?@75:0) */
  w075  = (w068?w075:0);
  /* #874: @72 = (@72?@75:0) */
  w072  = (w072?w075:0);
  /* #875: @73 = (@73?@72:0) */
  w073  = (w073?w072:0);
  /* #876: @113 = (@113+@73) */
  w113 += w073;
  /* #877: @71 = (@71*@59) */
  w071 *= w059;
  /* #878: @60 = (@60?@71:0) */
  w060  = (w060?w071:0);
  /* #879: @68 = (@68?@60:0) */
  w068  = (w068?w060:0);
  /* #880: @69 = (@69?@68:0) */
  w069  = (w069?w068:0);
  /* #881: @113 = (@113+@69) */
  w113 += w069;
  /* #882: @62 = (@62*@113) */
  w062 *= w113;
  /* #883: @27 = (@27*@62) */
  w027 *= w062;
  /* #884: (@115[0] += @27) */
  for (rr=w115+0, cs=(&w027); rr!=w115+1; rr+=1) *rr += *cs++;
  /* #885: output[1][0] = @115 */
  casadi_copy(w115, 5, res[1]);
  /* #886: @67 = (@67*@7) */
  w067 *= w007;
  /* #887: output[2][0] = @67 */
  if (res[2]) res[2][0] = w067;
  return 0;
}

/* amon_model_expl_vde_adj:(i0[18],i1[18],i2[5],i3)->(o0[23]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w1=w+260, w2, *w5=w+284, *w6=w+302;
  const casadi_real **arg1=arg+4, *wr0, *wr4;
  /* #0: @0 = input[0][0] */
  wr0 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = input[2][0] */
  casadi_copy(arg[2], 5, w1);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = zeros(18x1,0nz) */
  /* #4: @4 = input[1][0] */
  wr4 = arg[1] ? arg[1] : casadi_zeros;
  /* #5: {@5, @6, NULL} = adj1_f(@0, @1, @2, @3, @4) */
  arg1[0]=wr0;
  arg1[1]=w1;
  arg1[2]=(&w2);
  arg1[3]=0;
  arg1[4]=wr4;
  res1[0]=w5;
  res1[1]=w6;
  res1[2]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][0] = @5 */
  casadi_copy(w5, 18, res[0]);
  /* #7: output[0][1] = @6 */
  if (res[0]) casadi_copy(w6, 5, res[0]+18);
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int amon_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void amon_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int amon_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void amon_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void amon_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void amon_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int amon_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int amon_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real amon_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* amon_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* amon_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* amon_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* amon_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int amon_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 307;
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 307*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
