/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) amon_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 3, 5, 6, 0, 1,
  2, 1, 2, 2};
static const casadi_int casadi_s3[12] = 
  {3, 3, 0, 1, 3, 6, 0, 0,
  1, 0, 1, 2};
static const casadi_int casadi_s4[3] = {13, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[3] = {0, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[3] = {0., 1., 0.};
static const casadi_real casadi_c2[3] = {0., -1., 0.};
static const casadi_real casadi_c3[3] = {1., 0., 0.};
static const casadi_real casadi_c4[3] = {-1., 0., 0.};
static const casadi_real casadi_c5[3] = {2.5000000000000001e-02, 0., -1.4999999999999999e-01};
static const casadi_real casadi_c6[3] = {-2.5000000000000001e-02, 0., -1.4999999999999999e-01};
static const casadi_real casadi_c7[3] = {0., 2.5000000000000001e-02, -1.4999999999999999e-01};
static const casadi_real casadi_c8[3] = {0., -2.5000000000000001e-02, -1.4999999999999999e-01};
static const casadi_real casadi_c9[9] = 
  {3.4393020000000003e-02, 0., 0., 0., 3.9167399999999998e-02, 0., 0., 0.,
  2.8093010000000002e-02};

static const casadi_real casadi_zeros[13] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* f:(i0[13],i1[5])->(o0[13]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w01=w+17, *w02=w+20, w03, w04, w05, w06, w07, w08, w09, w10, *w11=w+31;
  casadi_real *w12=w+34, *w13=w+37, *w14=w+40, *w15=w+49, *w16=w+58, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, w37, w38, *w39=w+85, *w40=w+89, *w41=w+93, *w42=w+97, *w43=w+101, *w44=w+105, *w45=w+121;
  const casadi_real *cs, *ct, *ss, *wr00, *wr01, *wr11, *wr15, *wr40;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w01);
  /* #4: @2 = zeros(3x1) */
  casadi_clear(w02, 3);
  /* #5: @3 = 1 */
  w03 = 1.;
  /* #6: @4 = @0[8] */
  w04 = wr00[8];
  /* #7: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #8: @6 = @0[9] */
  w06 = wr00[9];
  /* #9: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #10: @5 = (@5+@7) */
  w05 += w07;
  /* #11: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #12: @3 = (@3-@5) */
  w03 -= w05;
  /* #13: @5 = @0[7] */
  w05 = wr00[7];
  /* #14: @7 = (@5*@4) */
  w07  = (w05*w04);
  /* #15: @8 = @0[6] */
  w08 = wr00[6];
  /* #16: @9 = (@8*@6) */
  w09  = (w08*w06);
  /* #17: @7 = (@7-@9) */
  w07 -= w09;
  /* #18: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #19: @9 = (@5*@6) */
  w09  = (w05*w06);
  /* #20: @10 = (@8*@4) */
  w10  = (w08*w04);
  /* #21: @9 = (@9+@10) */
  w09 += w10;
  /* #22: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #23: @11 = horzcat(@3, @7, @9) */
  rr=w11;
  *rr++ = w03;
  *rr++ = w07;
  *rr++ = w09;
  /* #24: @11 = @11' */
  /* #25: @3 = (@5*@4) */
  w03  = (w05*w04);
  /* #26: @7 = (@8*@6) */
  w07  = (w08*w06);
  /* #27: @3 = (@3+@7) */
  w03 += w07;
  /* #28: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #29: @7 = 1 */
  w07 = 1.;
  /* #30: @9 = sq(@5) */
  w09 = casadi_sq( w05 );
  /* #31: @10 = sq(@6) */
  w10 = casadi_sq( w06 );
  /* #32: @9 = (@9+@10) */
  w09 += w10;
  /* #33: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #34: @7 = (@7-@9) */
  w07 -= w09;
  /* #35: @9 = (@4*@6) */
  w09  = (w04*w06);
  /* #36: @10 = (@8*@5) */
  w10  = (w08*w05);
  /* #37: @9 = (@9-@10) */
  w09 -= w10;
  /* #38: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #39: @12 = horzcat(@3, @7, @9) */
  rr=w12;
  *rr++ = w03;
  *rr++ = w07;
  *rr++ = w09;
  /* #40: @12 = @12' */
  /* #41: @3 = (@5*@6) */
  w03  = (w05*w06);
  /* #42: @7 = (@8*@4) */
  w07  = (w08*w04);
  /* #43: @3 = (@3-@7) */
  w03 -= w07;
  /* #44: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #45: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #46: @8 = (@8*@5) */
  w08 *= w05;
  /* #47: @6 = (@6+@8) */
  w06 += w08;
  /* #48: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #49: @8 = 1 */
  w08 = 1.;
  /* #50: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #51: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #52: @5 = (@5+@4) */
  w05 += w04;
  /* #53: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #54: @8 = (@8-@5) */
  w08 -= w05;
  /* #55: @13 = horzcat(@3, @6, @8) */
  rr=w13;
  *rr++ = w03;
  *rr++ = w06;
  *rr++ = w08;
  /* #56: @13 = @13' */
  /* #57: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #58: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #59: @3 = 0 */
  w03 = 0.;
  /* #60: @6 = 0 */
  w06 = 0.;
  /* #61: @8 = 100 */
  w08 = 100.;
  /* #62: @16 = input[1][0] */
  casadi_copy(arg[1], 5, w16);
  /* #63: @5 = @16[0] */
  for (rr=(&w05), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #64: @4 = 0 */
  w04 = 0.;
  /* #65: @5 = fmax(@5,@4) */
  w05  = casadi_fmax(w05,w04);
  /* #66: @4 = 100 */
  w04 = 100.;
  /* #67: @5 = fmin(@5,@4) */
  w05  = casadi_fmin(w05,w04);
  /* #68: @8 = (@8<@5) */
  w08  = (w08<w05);
  /* #69: @4 = 27 */
  w04 = 27.;
  /* #70: @4 = (@8?@4:0) */
  w04  = (w08?w04:0);
  /* #71: @8 = (!@8) */
  w08 = (! w08 );
  /* #72: @7 = 0 */
  w07 = 0.;
  /* #73: @7 = (@5<@7) */
  w07  = (w05<w07);
  /* #74: @7 = (!@7) */
  w07 = (! w07 );
  /* #75: @9 = 90 */
  w09 = 90.;
  /* #76: @9 = (@9<=@5) */
  w09  = (w09<=w05);
  /* #77: @10 = 100 */
  w10 = 100.;
  /* #78: @10 = (@5<=@10) */
  w10  = (w05<=w10);
  /* #79: @9 = (@9&&@10) */
  w09  = (w09&&w10);
  /* #80: @10 = 26.753 */
  w10 = 2.6752962991109627e+01;
  /* #81: @17 = 0.0247037 */
  w17 = 2.4703700889037349e-02;
  /* #82: @18 = 90 */
  w18 = 90.;
  /* #83: @18 = (@5-@18) */
  w18  = (w05-w18);
  /* #84: @17 = (@17*@18) */
  w17 *= w18;
  /* #85: @10 = (@10+@17) */
  w10 += w17;
  /* #86: @10 = (@9?@10:0) */
  w10  = (w09?w10:0);
  /* #87: @9 = (!@9) */
  w09 = (! w09 );
  /* #88: @17 = 85 */
  w17 = 85.;
  /* #89: @17 = (@17<=@5) */
  w17  = (w17<=w05);
  /* #90: @18 = 90 */
  w18 = 90.;
  /* #91: @18 = (@5<=@18) */
  w18  = (w05<=w18);
  /* #92: @17 = (@17&&@18) */
  w17  = (w17&&w18);
  /* #93: @18 = 24.7588 */
  w18 = 2.4758844578012344e+01;
  /* #94: @19 = 0.398824 */
  w19 = 3.9882368261945655e-01;
  /* #95: @20 = 85 */
  w20 = 85.;
  /* #96: @20 = (@5-@20) */
  w20  = (w05-w20);
  /* #97: @19 = (@19*@20) */
  w19 *= w20;
  /* #98: @18 = (@18+@19) */
  w18 += w19;
  /* #99: @18 = (@17?@18:0) */
  w18  = (w17?w18:0);
  /* #100: @17 = (!@17) */
  w17 = (! w17 );
  /* #101: @19 = 80 */
  w19 = 80.;
  /* #102: @19 = (@19<=@5) */
  w19  = (w19<=w05);
  /* #103: @20 = 85 */
  w20 = 85.;
  /* #104: @20 = (@5<=@20) */
  w20  = (w05<=w20);
  /* #105: @19 = (@19&&@20) */
  w19  = (w19&&w20);
  /* #106: @20 = 22.8389 */
  w20 = 2.2838908040823828e+01;
  /* #107: @21 = 0.383987 */
  w21 = 3.8398730743770315e-01;
  /* #108: @22 = 80 */
  w22 = 80.;
  /* #109: @22 = (@5-@22) */
  w22  = (w05-w22);
  /* #110: @21 = (@21*@22) */
  w21 *= w22;
  /* #111: @20 = (@20+@21) */
  w20 += w21;
  /* #112: @20 = (@19?@20:0) */
  w20  = (w19?w20:0);
  /* #113: @19 = (!@19) */
  w19 = (! w19 );
  /* #114: @21 = 75 */
  w21 = 75.;
  /* #115: @21 = (@21<=@5) */
  w21  = (w21<=w05);
  /* #116: @22 = 80 */
  w22 = 80.;
  /* #117: @22 = (@5<=@22) */
  w22  = (w05<=w22);
  /* #118: @21 = (@21&&@22) */
  w21  = (w21&&w22);
  /* #119: @22 = 20.8242 */
  w22 = 2.0824175499723022e+01;
  /* #120: @23 = 0.402947 */
  w23 = 4.0294650822016109e-01;
  /* #121: @24 = 75 */
  w24 = 75.;
  /* #122: @24 = (@5-@24) */
  w24  = (w05-w24);
  /* #123: @23 = (@23*@24) */
  w23 *= w24;
  /* #124: @22 = (@22+@23) */
  w22 += w23;
  /* #125: @22 = (@21?@22:0) */
  w22  = (w21?w22:0);
  /* #126: @21 = (!@21) */
  w21 = (! w21 );
  /* #127: @23 = 70 */
  w23 = 70.;
  /* #128: @23 = (@23<=@5) */
  w23  = (w23<=w05);
  /* #129: @24 = 75 */
  w24 = 75.;
  /* #130: @24 = (@5<=@24) */
  w24  = (w05<=w24);
  /* #131: @23 = (@23&&@24) */
  w23  = (w23&&w24);
  /* #132: @24 = 18.3959 */
  w24 = 1.8395945471821904e+01;
  /* #133: @25 = 0.485646 */
  w25 = 4.8564600558022375e-01;
  /* #134: @26 = 70 */
  w26 = 70.;
  /* #135: @26 = (@5-@26) */
  w26  = (w05-w26);
  /* #136: @25 = (@25*@26) */
  w25 *= w26;
  /* #137: @24 = (@24+@25) */
  w24 += w25;
  /* #138: @24 = (@23?@24:0) */
  w24  = (w23?w24:0);
  /* #139: @23 = (!@23) */
  w23 = (! w23 );
  /* #140: @25 = 60 */
  w25 = 60.;
  /* #141: @25 = (@25<=@5) */
  w25  = (w25<=w05);
  /* #142: @26 = 70 */
  w26 = 70.;
  /* #143: @26 = (@5<=@26) */
  w26  = (w05<=w26);
  /* #144: @25 = (@25&&@26) */
  w25  = (w25&&w26);
  /* #145: @26 = 14.7408 */
  w26 = 1.4740834272959603e+01;
  /* #146: @27 = 0.365511 */
  w27 = 3.6551111988623008e-01;
  /* #147: @28 = 60 */
  w28 = 60.;
  /* #148: @28 = (@5-@28) */
  w28  = (w05-w28);
  /* #149: @27 = (@27*@28) */
  w27 *= w28;
  /* #150: @26 = (@26+@27) */
  w26 += w27;
  /* #151: @26 = (@25?@26:0) */
  w26  = (w25?w26:0);
  /* #152: @25 = (!@25) */
  w25 = (! w25 );
  /* #153: @27 = 50 */
  w27 = 50.;
  /* #154: @27 = (@27<=@5) */
  w27  = (w27<=w05);
  /* #155: @28 = 60 */
  w28 = 60.;
  /* #156: @28 = (@5<=@28) */
  w28  = (w05<=w28);
  /* #157: @27 = (@27&&@28) */
  w27  = (w27&&w28);
  /* #158: @28 = 12.0425 */
  w28 = 1.2042451609558308e+01;
  /* #159: @29 = 0.269838 */
  w29 = 2.6983826634012953e-01;
  /* #160: @30 = 50 */
  w30 = 50.;
  /* #161: @30 = (@5-@30) */
  w30  = (w05-w30);
  /* #162: @29 = (@29*@30) */
  w29 *= w30;
  /* #163: @28 = (@28+@29) */
  w28 += w29;
  /* #164: @28 = (@27?@28:0) */
  w28  = (w27?w28:0);
  /* #165: @27 = (!@27) */
  w27 = (! w27 );
  /* #166: @29 = 40 */
  w29 = 40.;
  /* #167: @29 = (@29<=@5) */
  w29  = (w29<=w05);
  /* #168: @30 = 50 */
  w30 = 50.;
  /* #169: @30 = (@5<=@30) */
  w30  = (w05<=w30);
  /* #170: @29 = (@29&&@30) */
  w29  = (w29&&w30);
  /* #171: @30 = 9.61328 */
  w30 = 9.6132801575173321e+00;
  /* #172: @31 = 0.242917 */
  w31 = 2.4291714520409755e-01;
  /* #173: @32 = 40 */
  w32 = 40.;
  /* #174: @32 = (@5-@32) */
  w32  = (w05-w32);
  /* #175: @31 = (@31*@32) */
  w31 *= w32;
  /* #176: @30 = (@30+@31) */
  w30 += w31;
  /* #177: @30 = (@29?@30:0) */
  w30  = (w29?w30:0);
  /* #178: @29 = (!@29) */
  w29 = (! w29 );
  /* #179: @31 = 30 */
  w31 = 30.;
  /* #180: @31 = (@31<=@5) */
  w31  = (w31<=w05);
  /* #181: @32 = 40 */
  w32 = 40.;
  /* #182: @32 = (@5<=@32) */
  w32  = (w05<=w32);
  /* #183: @31 = (@31&&@32) */
  w31  = (w31&&w32);
  /* #184: @32 = 7.04574 */
  w32 = 7.0457390494971124e+00;
  /* #185: @33 = 0.256754 */
  w33 = 2.5675411080202198e-01;
  /* #186: @34 = 30 */
  w34 = 30.;
  /* #187: @34 = (@5-@34) */
  w34  = (w05-w34);
  /* #188: @33 = (@33*@34) */
  w33 *= w34;
  /* #189: @32 = (@32+@33) */
  w32 += w33;
  /* #190: @32 = (@31?@32:0) */
  w32  = (w31?w32:0);
  /* #191: @31 = (!@31) */
  w31 = (! w31 );
  /* #192: @33 = 20 */
  w33 = 20.;
  /* #193: @33 = (@33<=@5) */
  w33  = (w33<=w05);
  /* #194: @34 = 30 */
  w34 = 30.;
  /* #195: @34 = (@5<=@34) */
  w34  = (w05<=w34);
  /* #196: @33 = (@33&&@34) */
  w33  = (w33&&w34);
  /* #197: @34 = 4.24854 */
  w34 = 4.2485368817013320e+00;
  /* #198: @35 = 0.27972 */
  w35 = 2.7972021677957803e-01;
  /* #199: @36 = 20 */
  w36 = 20.;
  /* #200: @36 = (@5-@36) */
  w36  = (w05-w36);
  /* #201: @35 = (@35*@36) */
  w35 *= w36;
  /* #202: @34 = (@34+@35) */
  w34 += w35;
  /* #203: @34 = (@33?@34:0) */
  w34  = (w33?w34:0);
  /* #204: @33 = (!@33) */
  w33 = (! w33 );
  /* #205: @35 = 10 */
  w35 = 10.;
  /* #206: @35 = (@35<=@5) */
  w35  = (w35<=w05);
  /* #207: @36 = 20 */
  w36 = 20.;
  /* #208: @36 = (@5<=@36) */
  w36  = (w05<=w36);
  /* #209: @35 = (@35&&@36) */
  w35  = (w35&&w36);
  /* #210: @36 = 1.46239 */
  w36 = 1.4623894660200982e+00;
  /* #211: @37 = 0.278615 */
  w37 = 2.7861474156812338e-01;
  /* #212: @38 = 10 */
  w38 = 10.;
  /* #213: @38 = (@5-@38) */
  w38  = (w05-w38);
  /* #214: @37 = (@37*@38) */
  w37 *= w38;
  /* #215: @36 = (@36+@37) */
  w36 += w37;
  /* #216: @36 = (@35?@36:0) */
  w36  = (w35?w36:0);
  /* #217: @35 = (!@35) */
  w35 = (! w35 );
  /* #218: @37 = 0 */
  w37 = 0.;
  /* #219: @37 = (@37<=@5) */
  w37  = (w37<=w05);
  /* #220: @38 = 10 */
  w38 = 10.;
  /* #221: @38 = (@5<=@38) */
  w38  = (w05<=w38);
  /* #222: @37 = (@37&&@38) */
  w37  = (w37&&w38);
  /* #223: @38 = 0.146239 */
  w38 = 1.4623894660200981e-01;
  /* #224: @38 = (@38*@5) */
  w38 *= w05;
  /* #225: @37 = (@37?@38:0) */
  w37  = (w37?w38:0);
  /* #226: @35 = (@35?@37:0) */
  w35  = (w35?w37:0);
  /* #227: @36 = (@36+@35) */
  w36 += w35;
  /* #228: @33 = (@33?@36:0) */
  w33  = (w33?w36:0);
  /* #229: @34 = (@34+@33) */
  w34 += w33;
  /* #230: @31 = (@31?@34:0) */
  w31  = (w31?w34:0);
  /* #231: @32 = (@32+@31) */
  w32 += w31;
  /* #232: @29 = (@29?@32:0) */
  w29  = (w29?w32:0);
  /* #233: @30 = (@30+@29) */
  w30 += w29;
  /* #234: @27 = (@27?@30:0) */
  w27  = (w27?w30:0);
  /* #235: @28 = (@28+@27) */
  w28 += w27;
  /* #236: @25 = (@25?@28:0) */
  w25  = (w25?w28:0);
  /* #237: @26 = (@26+@25) */
  w26 += w25;
  /* #238: @23 = (@23?@26:0) */
  w23  = (w23?w26:0);
  /* #239: @24 = (@24+@23) */
  w24 += w23;
  /* #240: @21 = (@21?@24:0) */
  w21  = (w21?w24:0);
  /* #241: @22 = (@22+@21) */
  w22 += w21;
  /* #242: @19 = (@19?@22:0) */
  w19  = (w19?w22:0);
  /* #243: @20 = (@20+@19) */
  w20 += w19;
  /* #244: @17 = (@17?@20:0) */
  w17  = (w17?w20:0);
  /* #245: @18 = (@18+@17) */
  w18 += w17;
  /* #246: @9 = (@9?@18:0) */
  w09  = (w09?w18:0);
  /* #247: @10 = (@10+@9) */
  w10 += w09;
  /* #248: @7 = (@7?@10:0) */
  w07  = (w07?w10:0);
  /* #249: @8 = (@8?@7:0) */
  w08  = (w08?w07:0);
  /* #250: @4 = (@4+@8) */
  w04 += w08;
  /* #251: @11 = vertcat(@3, @6, @4) */
  rr=w11;
  *rr++ = w03;
  *rr++ = w06;
  *rr++ = w04;
  /* #252: @12 = [0, 1, 0] */
  casadi_copy(casadi_c1, 3, w12);
  /* #253: @3 = 0.04454 */
  w03 = 4.4540000000000003e-02;
  /* #254: @3 = (@3*@4) */
  w03 *= w04;
  /* #255: @6 = 3.14159 */
  w06 = 3.1415926535897931e+00;
  /* #256: @8 = @16[1] */
  for (rr=(&w08), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #257: @7 = -34 */
  w07 = -34.;
  /* #258: @8 = fmax(@8,@7) */
  w08  = casadi_fmax(w08,w07);
  /* #259: @7 = 34 */
  w07 = 34.;
  /* #260: @8 = fmin(@8,@7) */
  w08  = casadi_fmin(w08,w07);
  /* #261: @6 = (@6*@8) */
  w06 *= w08;
  /* #262: @8 = 180 */
  w08 = 180.;
  /* #263: @6 = (@6/@8) */
  w06 /= w08;
  /* #264: @8 = sin(@6) */
  w08 = sin( w06 );
  /* #265: @3 = (@3*@8) */
  w03 *= w08;
  /* #266: @12 = (@12*@3) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) *= w03;
  /* #267: @13 = [0, -1, 0] */
  casadi_copy(casadi_c2, 3, w13);
  /* #268: @3 = 0.04454 */
  w03 = 4.4540000000000003e-02;
  /* #269: @3 = (@3*@4) */
  w03 *= w04;
  /* #270: @8 = 3.14159 */
  w08 = 3.1415926535897931e+00;
  /* #271: @7 = @16[2] */
  for (rr=(&w07), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #272: @10 = -34 */
  w10 = -34.;
  /* #273: @7 = fmax(@7,@10) */
  w07  = casadi_fmax(w07,w10);
  /* #274: @10 = 34 */
  w10 = 34.;
  /* #275: @7 = fmin(@7,@10) */
  w07  = casadi_fmin(w07,w10);
  /* #276: @8 = (@8*@7) */
  w08 *= w07;
  /* #277: @7 = 180 */
  w07 = 180.;
  /* #278: @8 = (@8/@7) */
  w08 /= w07;
  /* #279: @7 = sin(@8) */
  w07 = sin( w08 );
  /* #280: @3 = (@3*@7) */
  w03 *= w07;
  /* #281: @13 = (@13*@3) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) *= w03;
  /* #282: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #283: @13 = [1, 0, 0] */
  casadi_copy(casadi_c3, 3, w13);
  /* #284: @3 = 0.04454 */
  w03 = 4.4540000000000003e-02;
  /* #285: @3 = (@3*@4) */
  w03 *= w04;
  /* #286: @7 = 3.14159 */
  w07 = 3.1415926535897931e+00;
  /* #287: @10 = @16[3] */
  for (rr=(&w10), cs=w16+3; cs!=w16+4; cs+=1) *rr++ = *cs;
  /* #288: @9 = -34 */
  w09 = -34.;
  /* #289: @10 = fmax(@10,@9) */
  w10  = casadi_fmax(w10,w09);
  /* #290: @9 = 34 */
  w09 = 34.;
  /* #291: @10 = fmin(@10,@9) */
  w10  = casadi_fmin(w10,w09);
  /* #292: @7 = (@7*@10) */
  w07 *= w10;
  /* #293: @10 = 180 */
  w10 = 180.;
  /* #294: @7 = (@7/@10) */
  w07 /= w10;
  /* #295: @10 = sin(@7) */
  w10 = sin( w07 );
  /* #296: @3 = (@3*@10) */
  w03 *= w10;
  /* #297: @13 = (@13*@3) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) *= w03;
  /* #298: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #299: @13 = [-1, 0, 0] */
  casadi_copy(casadi_c4, 3, w13);
  /* #300: @3 = 0.04454 */
  w03 = 4.4540000000000003e-02;
  /* #301: @3 = (@3*@4) */
  w03 *= w04;
  /* #302: @10 = 3.14159 */
  w10 = 3.1415926535897931e+00;
  /* #303: @9 = @16[4] */
  for (rr=(&w09), cs=w16+4; cs!=w16+5; cs+=1) *rr++ = *cs;
  /* #304: @18 = -34 */
  w18 = -34.;
  /* #305: @9 = fmax(@9,@18) */
  w09  = casadi_fmax(w09,w18);
  /* #306: @18 = 34 */
  w18 = 34.;
  /* #307: @9 = fmin(@9,@18) */
  w09  = casadi_fmin(w09,w18);
  /* #308: @10 = (@10*@9) */
  w10 *= w09;
  /* #309: @9 = 180 */
  w09 = 180.;
  /* #310: @10 = (@10/@9) */
  w10 /= w09;
  /* #311: @9 = sin(@10) */
  w09 = sin( w10 );
  /* #312: @3 = (@3*@9) */
  w03 *= w09;
  /* #313: @13 = (@13*@3) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) *= w03;
  /* #314: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #315: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #316: @2 = mac(@15,@11,@2) */
  for (i=0, rr=w02; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w15+j, ct=w11+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #317: @3 = 2.485 */
  w03 = 2.4849999999999999e+00;
  /* #318: @2 = (@2/@3) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) /= w03;
  /* #319: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #320: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #321: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #322: @39 = zeros(4x1) */
  casadi_clear(w39, 4);
  /* #323: @9 = 0 */
  w09 = 0.;
  /* #324: @18 = @0[10] */
  w18 = wr00[10];
  /* #325: @17 = (-@18) */
  w17 = (- w18 );
  /* #326: @20 = @0[11] */
  w20 = wr00[11];
  /* #327: @19 = (-@20) */
  w19 = (- w20 );
  /* #328: @22 = @0[12] */
  w22 = wr00[12];
  /* #329: @21 = (-@22) */
  w21 = (- w22 );
  /* #330: @40 = horzcat(@9, @17, @19, @21) */
  rr=w40;
  *rr++ = w09;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w21;
  /* #331: @40 = @40' */
  /* #332: @9 = 0 */
  w09 = 0.;
  /* #333: @17 = (-@20) */
  w17 = (- w20 );
  /* #334: @41 = horzcat(@18, @9, @22, @17) */
  rr=w41;
  *rr++ = w18;
  *rr++ = w09;
  *rr++ = w22;
  *rr++ = w17;
  /* #335: @41 = @41' */
  /* #336: @9 = (-@22) */
  w09 = (- w22 );
  /* #337: @17 = 0 */
  w17 = 0.;
  /* #338: @42 = horzcat(@20, @9, @17, @18) */
  rr=w42;
  *rr++ = w20;
  *rr++ = w09;
  *rr++ = w17;
  *rr++ = w18;
  /* #339: @42 = @42' */
  /* #340: @18 = (-@18) */
  w18 = (- w18 );
  /* #341: @9 = 0 */
  w09 = 0.;
  /* #342: @43 = horzcat(@22, @20, @18, @9) */
  rr=w43;
  *rr++ = w22;
  *rr++ = w20;
  *rr++ = w18;
  *rr++ = w09;
  /* #343: @43 = @43' */
  /* #344: @44 = horzcat(@40, @41, @42, @43) */
  rr=w44;
  for (i=0, cs=w40; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<4; ++i) *rr++ = *cs++;
  /* #345: @45 = @44' */
  for (i=0, rr=w45, cs=w44; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #346: @40 = @0[6:10] */
  wr40 = wr00+6;
  /* #347: @39 = mac(@45,@40,@39) */
  for (i=0, rr=w39; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w45+j, ct=wr40+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #348: @39 = (@3*@39) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) (*rr++)  = (w03*(*cs++));
  /* #349: output[0][2] = @39 */
  if (res[0]) casadi_copy(w39, 4, res[0]+6);
  /* #350: @1 = [0.025, 0, -0.15] */
  casadi_copy(casadi_c5, 3, w01);
  /* #351: @3 = @1[1] */
  for (rr=(&w03), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #352: @2 = [0, 1, 0] */
  casadi_copy(casadi_c1, 3, w02);
  /* #353: @22 = 0.04454 */
  w22 = 4.4540000000000003e-02;
  /* #354: @22 = (@22*@4) */
  w22 *= w04;
  /* #355: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #356: @22 = (@22*@6) */
  w22 *= w06;
  /* #357: @2 = (@2*@22) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) *= w22;
  /* #358: @22 = @2[2] */
  for (rr=(&w22), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #359: @6 = (@3*@22) */
  w06  = (w03*w22);
  /* #360: @20 = @1[2] */
  for (rr=(&w20), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #361: @18 = @2[1] */
  for (rr=(&w18), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #362: @9 = (@20*@18) */
  w09  = (w20*w18);
  /* #363: @6 = (@6-@9) */
  w06 -= w09;
  /* #364: @9 = @2[0] */
  for (rr=(&w09), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #365: @20 = (@20*@9) */
  w20 *= w09;
  /* #366: @17 = @1[0] */
  for (rr=(&w17), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #367: @22 = (@17*@22) */
  w22  = (w17*w22);
  /* #368: @20 = (@20-@22) */
  w20 -= w22;
  /* #369: @17 = (@17*@18) */
  w17 *= w18;
  /* #370: @3 = (@3*@9) */
  w03 *= w09;
  /* #371: @17 = (@17-@3) */
  w17 -= w03;
  /* #372: @1 = vertcat(@6, @20, @17) */
  rr=w01;
  *rr++ = w06;
  *rr++ = w20;
  *rr++ = w17;
  /* #373: @2 = [-0.025, 0, -0.15] */
  casadi_copy(casadi_c6, 3, w02);
  /* #374: @6 = @2[1] */
  for (rr=(&w06), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #375: @11 = [0, -1, 0] */
  casadi_copy(casadi_c2, 3, w11);
  /* #376: @20 = 0.04454 */
  w20 = 4.4540000000000003e-02;
  /* #377: @20 = (@20*@4) */
  w20 *= w04;
  /* #378: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #379: @20 = (@20*@8) */
  w20 *= w08;
  /* #380: @11 = (@11*@20) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) *= w20;
  /* #381: @20 = @11[2] */
  for (rr=(&w20), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #382: @8 = (@6*@20) */
  w08  = (w06*w20);
  /* #383: @17 = @2[2] */
  for (rr=(&w17), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #384: @3 = @11[1] */
  for (rr=(&w03), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #385: @9 = (@17*@3) */
  w09  = (w17*w03);
  /* #386: @8 = (@8-@9) */
  w08 -= w09;
  /* #387: @9 = @11[0] */
  for (rr=(&w09), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #388: @17 = (@17*@9) */
  w17 *= w09;
  /* #389: @18 = @2[0] */
  for (rr=(&w18), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #390: @20 = (@18*@20) */
  w20  = (w18*w20);
  /* #391: @17 = (@17-@20) */
  w17 -= w20;
  /* #392: @18 = (@18*@3) */
  w18 *= w03;
  /* #393: @6 = (@6*@9) */
  w06 *= w09;
  /* #394: @18 = (@18-@6) */
  w18 -= w06;
  /* #395: @2 = vertcat(@8, @17, @18) */
  rr=w02;
  *rr++ = w08;
  *rr++ = w17;
  *rr++ = w18;
  /* #396: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #397: @2 = [0, 0.025, -0.15] */
  casadi_copy(casadi_c7, 3, w02);
  /* #398: @8 = @2[1] */
  for (rr=(&w08), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #399: @11 = [1, 0, 0] */
  casadi_copy(casadi_c3, 3, w11);
  /* #400: @17 = 0.04454 */
  w17 = 4.4540000000000003e-02;
  /* #401: @17 = (@17*@4) */
  w17 *= w04;
  /* #402: @7 = sin(@7) */
  w07 = sin( w07 );
  /* #403: @17 = (@17*@7) */
  w17 *= w07;
  /* #404: @11 = (@11*@17) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) *= w17;
  /* #405: @17 = @11[2] */
  for (rr=(&w17), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #406: @7 = (@8*@17) */
  w07  = (w08*w17);
  /* #407: @18 = @2[2] */
  for (rr=(&w18), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #408: @6 = @11[1] */
  for (rr=(&w06), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #409: @9 = (@18*@6) */
  w09  = (w18*w06);
  /* #410: @7 = (@7-@9) */
  w07 -= w09;
  /* #411: @9 = @11[0] */
  for (rr=(&w09), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #412: @18 = (@18*@9) */
  w18 *= w09;
  /* #413: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #414: @17 = (@3*@17) */
  w17  = (w03*w17);
  /* #415: @18 = (@18-@17) */
  w18 -= w17;
  /* #416: @3 = (@3*@6) */
  w03 *= w06;
  /* #417: @8 = (@8*@9) */
  w08 *= w09;
  /* #418: @3 = (@3-@8) */
  w03 -= w08;
  /* #419: @2 = vertcat(@7, @18, @3) */
  rr=w02;
  *rr++ = w07;
  *rr++ = w18;
  *rr++ = w03;
  /* #420: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #421: @2 = [0, -0.025, -0.15] */
  casadi_copy(casadi_c8, 3, w02);
  /* #422: @7 = @2[1] */
  for (rr=(&w07), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #423: @11 = [-1, 0, 0] */
  casadi_copy(casadi_c4, 3, w11);
  /* #424: @18 = 0.04454 */
  w18 = 4.4540000000000003e-02;
  /* #425: @18 = (@18*@4) */
  w18 *= w04;
  /* #426: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #427: @18 = (@18*@10) */
  w18 *= w10;
  /* #428: @11 = (@11*@18) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) *= w18;
  /* #429: @18 = @11[2] */
  for (rr=(&w18), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #430: @10 = (@7*@18) */
  w10  = (w07*w18);
  /* #431: @4 = @2[2] */
  for (rr=(&w04), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #432: @3 = @11[1] */
  for (rr=(&w03), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #433: @8 = (@4*@3) */
  w08  = (w04*w03);
  /* #434: @10 = (@10-@8) */
  w10 -= w08;
  /* #435: @8 = @11[0] */
  for (rr=(&w08), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #436: @4 = (@4*@8) */
  w04 *= w08;
  /* #437: @9 = @2[0] */
  for (rr=(&w09), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #438: @18 = (@9*@18) */
  w18  = (w09*w18);
  /* #439: @4 = (@4-@18) */
  w04 -= w18;
  /* #440: @9 = (@9*@3) */
  w09 *= w03;
  /* #441: @7 = (@7*@8) */
  w07 *= w08;
  /* #442: @9 = (@9-@7) */
  w09 -= w07;
  /* #443: @2 = vertcat(@10, @4, @9) */
  rr=w02;
  *rr++ = w10;
  *rr++ = w04;
  *rr++ = w09;
  /* #444: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #445: @10 = @0[11] */
  w10 = wr00[11];
  /* #446: @2 = zeros(3x1) */
  casadi_clear(w02, 3);
  /* #447: @15 = 
  [[0.034393, 0, 0], 
   [0, 0.0391674, 0], 
   [0, 0, 0.028093]] */
  wr15 = casadi_c9;
  /* #448: @11 = @0[10:13] */
  wr11 = wr00+10;
  /* #449: @2 = mac(@15,@11,@2) */
  for (i=0, rr=w02; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr15+j, ct=wr11+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #450: @4 = @2[2] */
  for (rr=(&w04), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #451: @9 = (@10*@4) */
  w09  = (w10*w04);
  /* #452: @7 = @0[12] */
  w07 = wr00[12];
  /* #453: @8 = @2[1] */
  for (rr=(&w08), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #454: @3 = (@7*@8) */
  w03  = (w07*w08);
  /* #455: @9 = (@9-@3) */
  w09 -= w03;
  /* #456: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #457: @7 = (@7*@3) */
  w07 *= w03;
  /* #458: @18 = @0[10] */
  w18 = wr00[10];
  /* #459: @4 = (@18*@4) */
  w04  = (w18*w04);
  /* #460: @7 = (@7-@4) */
  w07 -= w04;
  /* #461: @18 = (@18*@8) */
  w18 *= w08;
  /* #462: @10 = (@10*@3) */
  w10 *= w03;
  /* #463: @18 = (@18-@10) */
  w18 -= w10;
  /* #464: @2 = vertcat(@9, @7, @18) */
  rr=w02;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w18;
  /* #465: @1 = (@1-@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) -= (*cs++);
  /* #466: @15 = 
  [[0.034393, 0, 0], 
   [0, 0.0391674, 0], 
   [0, 0, 0.028093]] */
  wr15 = casadi_c9;
  /* #467: @1 = (@15\@1) */
  rr = w01;
  ss = wr15;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #468: output[0][3] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+10);
  return 0;
}

/* amon_model_expl_ode_fun:(i0[13],i1[5],i2[0])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w1=w+150, *w2=w+155;
  const casadi_real **arg1=arg+3, *wr0;
  /* #0: @0 = input[0][0] */
  wr0 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 5, w1);
  /* #2: @2 = f(@0, @1) */
  arg1[0]=wr0;
  arg1[1]=w1;
  res1[0]=w2;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #3: output[0][0] = @2 */
  casadi_copy(w2, 13, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void amon_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void amon_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void amon_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void amon_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int amon_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int amon_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real amon_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* amon_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* amon_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* amon_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* amon_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 168;
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 168*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
