/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) amon_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c10 CASADI_PREFIX(c10)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 3, 5, 6, 0, 1,
  2, 1, 2, 2};
static const casadi_int casadi_s3[12] = 
  {3, 3, 0, 1, 3, 6, 0, 0,
  1, 0, 1, 2};
static const casadi_int casadi_s4[3] = {18, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[3] = {1, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[3] = {0., 1., 0.};
static const casadi_real casadi_c2[3] = {0., -1., 0.};
static const casadi_real casadi_c3[3] = {1., 0., 0.};
static const casadi_real casadi_c4[3] = {-1., 0., 0.};
static const casadi_real casadi_c5[3] = {0., -1.5000000000000000e-03, 0.};
static const casadi_real casadi_c6[3] = {3.5000000000000003e-02, 0., -1.4000000000000001e-01};
static const casadi_real casadi_c7[3] = {-3.5000000000000003e-02, 0., -1.4000000000000001e-01};
static const casadi_real casadi_c8[3] = {0., 3.5000000000000003e-02, -1.4000000000000001e-01};
static const casadi_real casadi_c9[3] = {0., -3.5000000000000003e-02, -1.4000000000000001e-01};
static const casadi_real casadi_c10[9] = 
  {3.4393020000000003e-02, 0., 0., 0., 3.9167399999999998e-02, 0., 0., 0.,
  2.8093010000000002e-02};

static const casadi_real casadi_zeros[18] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* f:(i0[18],i1[5],i2)->(o0[18]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w01=w+22, *w02=w+25, w03, w04, w05, w06, w07, w08, w09, w10, *w11=w+36;
  casadi_real *w12=w+39, *w13=w+42, *w14=w+45, *w15=w+54, *w16=w+63, w17, *w18=w+68, *w19=w+72, *w20=w+76, *w21=w+80, *w22=w+84, *w23=w+100;
  casadi_real *w24=w+116, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, w37, w38, w39, w40, w41, w42, w43, w44, w45;
  const casadi_real *cs, *ct, *ss, *wr00, *wr01, *wr11, *wr15, *wr18;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w01);
  /* #4: @2 = zeros(3x1) */
  casadi_clear(w02, 3);
  /* #5: @3 = 1 */
  w03 = 1.;
  /* #6: @4 = @0[8] */
  w04 = wr00[8];
  /* #7: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #8: @6 = @0[9] */
  w06 = wr00[9];
  /* #9: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #10: @5 = (@5+@7) */
  w05 += w07;
  /* #11: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #12: @3 = (@3-@5) */
  w03 -= w05;
  /* #13: @5 = @0[7] */
  w05 = wr00[7];
  /* #14: @7 = (@5*@4) */
  w07  = (w05*w04);
  /* #15: @8 = @0[6] */
  w08 = wr00[6];
  /* #16: @9 = (@8*@6) */
  w09  = (w08*w06);
  /* #17: @7 = (@7-@9) */
  w07 -= w09;
  /* #18: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #19: @9 = (@5*@6) */
  w09  = (w05*w06);
  /* #20: @10 = (@8*@4) */
  w10  = (w08*w04);
  /* #21: @9 = (@9+@10) */
  w09 += w10;
  /* #22: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #23: @11 = horzcat(@3, @7, @9) */
  rr=w11;
  *rr++ = w03;
  *rr++ = w07;
  *rr++ = w09;
  /* #24: @11 = @11' */
  /* #25: @3 = (@5*@4) */
  w03  = (w05*w04);
  /* #26: @7 = (@8*@6) */
  w07  = (w08*w06);
  /* #27: @3 = (@3+@7) */
  w03 += w07;
  /* #28: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #29: @7 = 1 */
  w07 = 1.;
  /* #30: @9 = sq(@5) */
  w09 = casadi_sq( w05 );
  /* #31: @10 = sq(@6) */
  w10 = casadi_sq( w06 );
  /* #32: @9 = (@9+@10) */
  w09 += w10;
  /* #33: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #34: @7 = (@7-@9) */
  w07 -= w09;
  /* #35: @9 = (@4*@6) */
  w09  = (w04*w06);
  /* #36: @10 = (@8*@5) */
  w10  = (w08*w05);
  /* #37: @9 = (@9-@10) */
  w09 -= w10;
  /* #38: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #39: @12 = horzcat(@3, @7, @9) */
  rr=w12;
  *rr++ = w03;
  *rr++ = w07;
  *rr++ = w09;
  /* #40: @12 = @12' */
  /* #41: @3 = (@5*@6) */
  w03  = (w05*w06);
  /* #42: @7 = (@8*@4) */
  w07  = (w08*w04);
  /* #43: @3 = (@3-@7) */
  w03 -= w07;
  /* #44: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #45: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #46: @8 = (@8*@5) */
  w08 *= w05;
  /* #47: @6 = (@6+@8) */
  w06 += w08;
  /* #48: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #49: @8 = 1 */
  w08 = 1.;
  /* #50: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #51: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #52: @5 = (@5+@4) */
  w05 += w04;
  /* #53: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #54: @8 = (@8-@5) */
  w08 -= w05;
  /* #55: @13 = horzcat(@3, @6, @8) */
  rr=w13;
  *rr++ = w03;
  *rr++ = w06;
  *rr++ = w08;
  /* #56: @13 = @13' */
  /* #57: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #58: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #59: @3 = 0 */
  w03 = 0.;
  /* #60: @6 = 0 */
  w06 = 0.;
  /* #61: @8 = @0[13] */
  w08 = wr00[13];
  /* #62: @11 = vertcat(@3, @6, @8) */
  rr=w11;
  *rr++ = w03;
  *rr++ = w06;
  *rr++ = w08;
  /* #63: @12 = [0, 1, 0] */
  casadi_copy(casadi_c1, 3, w12);
  /* #64: @3 = 0.067146 */
  w03 = 6.7145999999999997e-02;
  /* #65: @3 = (@3*@8) */
  w03 *= w08;
  /* #66: @6 = @0[14] */
  w06 = wr00[14];
  /* #67: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #68: @3 = (@3*@6) */
  w03 *= w06;
  /* #69: @12 = (@12*@3) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) *= w03;
  /* #70: @13 = [0, -1, 0] */
  casadi_copy(casadi_c2, 3, w13);
  /* #71: @3 = 0.067146 */
  w03 = 6.7145999999999997e-02;
  /* #72: @3 = (@3*@8) */
  w03 *= w08;
  /* #73: @6 = @0[15] */
  w06 = wr00[15];
  /* #74: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #75: @3 = (@3*@6) */
  w03 *= w06;
  /* #76: @13 = (@13*@3) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) *= w03;
  /* #77: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #78: @13 = [1, 0, 0] */
  casadi_copy(casadi_c3, 3, w13);
  /* #79: @3 = 0.067146 */
  w03 = 6.7145999999999997e-02;
  /* #80: @3 = (@3*@8) */
  w03 *= w08;
  /* #81: @6 = @0[16] */
  w06 = wr00[16];
  /* #82: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #83: @3 = (@3*@6) */
  w03 *= w06;
  /* #84: @13 = (@13*@3) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) *= w03;
  /* #85: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #86: @13 = [-1, 0, 0] */
  casadi_copy(casadi_c4, 3, w13);
  /* #87: @3 = 0.067146 */
  w03 = 6.7145999999999997e-02;
  /* #88: @3 = (@3*@8) */
  w03 *= w08;
  /* #89: @6 = @0[17] */
  w06 = wr00[17];
  /* #90: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #91: @3 = (@3*@6) */
  w03 *= w06;
  /* #92: @13 = (@13*@3) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) *= w03;
  /* #93: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #94: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #95: @2 = mac(@15,@11,@2) */
  for (i=0, rr=w02; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w15+j, ct=w11+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #96: @3 = 2.485 */
  w03 = 2.4849999999999999e+00;
  /* #97: @2 = (@2/@3) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) /= w03;
  /* #98: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #99: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #100: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #101: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #102: @6 = 0 */
  w06 = 0.;
  /* #103: @5 = @0[10] */
  w05 = wr00[10];
  /* #104: @4 = (-@5) */
  w04 = (- w05 );
  /* #105: @7 = @0[11] */
  w07 = wr00[11];
  /* #106: @9 = (-@7) */
  w09 = (- w07 );
  /* #107: @10 = @0[12] */
  w10 = wr00[12];
  /* #108: @17 = (-@10) */
  w17 = (- w10 );
  /* #109: @18 = horzcat(@6, @4, @9, @17) */
  rr=w18;
  *rr++ = w06;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w17;
  /* #110: @18 = @18' */
  /* #111: @6 = 0 */
  w06 = 0.;
  /* #112: @4 = (-@7) */
  w04 = (- w07 );
  /* #113: @19 = horzcat(@5, @6, @10, @4) */
  rr=w19;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w10;
  *rr++ = w04;
  /* #114: @19 = @19' */
  /* #115: @6 = (-@10) */
  w06 = (- w10 );
  /* #116: @4 = 0 */
  w04 = 0.;
  /* #117: @20 = horzcat(@7, @6, @4, @5) */
  rr=w20;
  *rr++ = w07;
  *rr++ = w06;
  *rr++ = w04;
  *rr++ = w05;
  /* #118: @20 = @20' */
  /* #119: @5 = (-@5) */
  w05 = (- w05 );
  /* #120: @6 = 0 */
  w06 = 0.;
  /* #121: @21 = horzcat(@10, @7, @5, @6) */
  rr=w21;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w05;
  *rr++ = w06;
  /* #122: @21 = @21' */
  /* #123: @22 = horzcat(@18, @19, @20, @21) */
  rr=w22;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  /* #124: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #125: @18 = @0[6:10] */
  wr18 = wr00+6;
  /* #126: @16 = mac(@23,@18,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w23+j, ct=wr18+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #127: @16 = (@3*@16) */
  for (i=0, rr=w16, cs=w16; i<4; ++i) (*rr++)  = (w03*(*cs++));
  /* #128: output[0][2] = @16 */
  if (res[0]) casadi_copy(w16, 4, res[0]+6);
  /* #129: @1 = [0, -0.0015, 0] */
  casadi_copy(casadi_c5, 3, w01);
  /* #130: @3 = @1[1] */
  for (rr=(&w03), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #131: @10 = @0[13] */
  w10 = wr00[13];
  /* #132: @3 = (@3*@10) */
  w03 *= w10;
  /* #133: @7 = @1[0] */
  for (rr=(&w07), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #134: @7 = (@7*@10) */
  w07 *= w10;
  /* #135: @7 = (-@7) */
  w07 = (- w07 );
  /* #136: @10 = 0 */
  w10 = 0.;
  /* #137: @1 = vertcat(@3, @7, @10) */
  rr=w01;
  *rr++ = w03;
  *rr++ = w07;
  *rr++ = w10;
  /* #138: @2 = [0.035, 0, -0.14] */
  casadi_copy(casadi_c6, 3, w02);
  /* #139: @3 = @2[1] */
  for (rr=(&w03), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #140: @11 = [0, 1, 0] */
  casadi_copy(casadi_c1, 3, w11);
  /* #141: @7 = 0.067146 */
  w07 = 6.7145999999999997e-02;
  /* #142: @7 = (@7*@8) */
  w07 *= w08;
  /* #143: @10 = @0[14] */
  w10 = wr00[14];
  /* #144: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #145: @7 = (@7*@10) */
  w07 *= w10;
  /* #146: @11 = (@11*@7) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) *= w07;
  /* #147: @7 = @11[2] */
  for (rr=(&w07), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #148: @10 = (@3*@7) */
  w10  = (w03*w07);
  /* #149: @5 = @2[2] */
  for (rr=(&w05), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #150: @6 = @11[1] */
  for (rr=(&w06), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #151: @4 = (@5*@6) */
  w04  = (w05*w06);
  /* #152: @10 = (@10-@4) */
  w10 -= w04;
  /* #153: @4 = @11[0] */
  for (rr=(&w04), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #154: @5 = (@5*@4) */
  w05 *= w04;
  /* #155: @9 = @2[0] */
  for (rr=(&w09), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #156: @7 = (@9*@7) */
  w07  = (w09*w07);
  /* #157: @5 = (@5-@7) */
  w05 -= w07;
  /* #158: @9 = (@9*@6) */
  w09 *= w06;
  /* #159: @3 = (@3*@4) */
  w03 *= w04;
  /* #160: @9 = (@9-@3) */
  w09 -= w03;
  /* #161: @2 = vertcat(@10, @5, @9) */
  rr=w02;
  *rr++ = w10;
  *rr++ = w05;
  *rr++ = w09;
  /* #162: @11 = [-0.035, 0, -0.14] */
  casadi_copy(casadi_c7, 3, w11);
  /* #163: @10 = @11[1] */
  for (rr=(&w10), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #164: @12 = [0, -1, 0] */
  casadi_copy(casadi_c2, 3, w12);
  /* #165: @5 = 0.067146 */
  w05 = 6.7145999999999997e-02;
  /* #166: @5 = (@5*@8) */
  w05 *= w08;
  /* #167: @9 = @0[15] */
  w09 = wr00[15];
  /* #168: @9 = sin(@9) */
  w09 = sin( w09 );
  /* #169: @5 = (@5*@9) */
  w05 *= w09;
  /* #170: @12 = (@12*@5) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) *= w05;
  /* #171: @5 = @12[2] */
  for (rr=(&w05), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #172: @9 = (@10*@5) */
  w09  = (w10*w05);
  /* #173: @3 = @11[2] */
  for (rr=(&w03), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #174: @4 = @12[1] */
  for (rr=(&w04), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #175: @6 = (@3*@4) */
  w06  = (w03*w04);
  /* #176: @9 = (@9-@6) */
  w09 -= w06;
  /* #177: @6 = @12[0] */
  for (rr=(&w06), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #178: @3 = (@3*@6) */
  w03 *= w06;
  /* #179: @7 = @11[0] */
  for (rr=(&w07), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #180: @5 = (@7*@5) */
  w05  = (w07*w05);
  /* #181: @3 = (@3-@5) */
  w03 -= w05;
  /* #182: @7 = (@7*@4) */
  w07 *= w04;
  /* #183: @10 = (@10*@6) */
  w10 *= w06;
  /* #184: @7 = (@7-@10) */
  w07 -= w10;
  /* #185: @11 = vertcat(@9, @3, @7) */
  rr=w11;
  *rr++ = w09;
  *rr++ = w03;
  *rr++ = w07;
  /* #186: @2 = (@2+@11) */
  for (i=0, rr=w02, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #187: @11 = [0, 0.035, -0.14] */
  casadi_copy(casadi_c8, 3, w11);
  /* #188: @9 = @11[1] */
  for (rr=(&w09), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #189: @12 = [1, 0, 0] */
  casadi_copy(casadi_c3, 3, w12);
  /* #190: @3 = 0.067146 */
  w03 = 6.7145999999999997e-02;
  /* #191: @3 = (@3*@8) */
  w03 *= w08;
  /* #192: @7 = @0[16] */
  w07 = wr00[16];
  /* #193: @7 = sin(@7) */
  w07 = sin( w07 );
  /* #194: @3 = (@3*@7) */
  w03 *= w07;
  /* #195: @12 = (@12*@3) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) *= w03;
  /* #196: @3 = @12[2] */
  for (rr=(&w03), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #197: @7 = (@9*@3) */
  w07  = (w09*w03);
  /* #198: @10 = @11[2] */
  for (rr=(&w10), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #199: @6 = @12[1] */
  for (rr=(&w06), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #200: @4 = (@10*@6) */
  w04  = (w10*w06);
  /* #201: @7 = (@7-@4) */
  w07 -= w04;
  /* #202: @4 = @12[0] */
  for (rr=(&w04), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #203: @10 = (@10*@4) */
  w10 *= w04;
  /* #204: @5 = @11[0] */
  for (rr=(&w05), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #205: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #206: @10 = (@10-@3) */
  w10 -= w03;
  /* #207: @5 = (@5*@6) */
  w05 *= w06;
  /* #208: @9 = (@9*@4) */
  w09 *= w04;
  /* #209: @5 = (@5-@9) */
  w05 -= w09;
  /* #210: @11 = vertcat(@7, @10, @5) */
  rr=w11;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w05;
  /* #211: @2 = (@2+@11) */
  for (i=0, rr=w02, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #212: @11 = [0, -0.035, -0.14] */
  casadi_copy(casadi_c9, 3, w11);
  /* #213: @7 = @11[1] */
  for (rr=(&w07), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #214: @12 = [-1, 0, 0] */
  casadi_copy(casadi_c4, 3, w12);
  /* #215: @10 = 0.067146 */
  w10 = 6.7145999999999997e-02;
  /* #216: @10 = (@10*@8) */
  w10 *= w08;
  /* #217: @5 = @0[17] */
  w05 = wr00[17];
  /* #218: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #219: @10 = (@10*@5) */
  w10 *= w05;
  /* #220: @12 = (@12*@10) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) *= w10;
  /* #221: @10 = @12[2] */
  for (rr=(&w10), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #222: @5 = (@7*@10) */
  w05  = (w07*w10);
  /* #223: @9 = @11[2] */
  for (rr=(&w09), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #224: @4 = @12[1] */
  for (rr=(&w04), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #225: @6 = (@9*@4) */
  w06  = (w09*w04);
  /* #226: @5 = (@5-@6) */
  w05 -= w06;
  /* #227: @6 = @12[0] */
  for (rr=(&w06), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #228: @9 = (@9*@6) */
  w09 *= w06;
  /* #229: @3 = @11[0] */
  for (rr=(&w03), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #230: @10 = (@3*@10) */
  w10  = (w03*w10);
  /* #231: @9 = (@9-@10) */
  w09 -= w10;
  /* #232: @3 = (@3*@4) */
  w03 *= w04;
  /* #233: @7 = (@7*@6) */
  w07 *= w06;
  /* #234: @3 = (@3-@7) */
  w03 -= w07;
  /* #235: @11 = vertcat(@5, @9, @3) */
  rr=w11;
  *rr++ = w05;
  *rr++ = w09;
  *rr++ = w03;
  /* #236: @2 = (@2+@11) */
  for (i=0, rr=w02, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #237: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #238: @5 = 0 */
  w05 = 0.;
  /* #239: @9 = 0 */
  w09 = 0.;
  /* #240: @3 = -0.00066188 */
  w03 = -6.6188000000000000e-04;
  /* #241: @3 = (@3*@8) */
  w03 *= w08;
  /* #242: @2 = vertcat(@5, @9, @3) */
  rr=w02;
  *rr++ = w05;
  *rr++ = w09;
  *rr++ = w03;
  /* #243: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #244: @5 = @0[11] */
  w05 = wr00[11];
  /* #245: @2 = zeros(3x1) */
  casadi_clear(w02, 3);
  /* #246: @15 = 
  [[0.034393, 0, 0], 
   [0, 0.0391674, 0], 
   [0, 0, 0.028093]] */
  wr15 = casadi_c10;
  /* #247: @11 = @0[10:13] */
  wr11 = wr00+10;
  /* #248: @2 = mac(@15,@11,@2) */
  for (i=0, rr=w02; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr15+j, ct=wr11+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #249: @9 = @2[2] */
  for (rr=(&w09), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #250: @3 = (@5*@9) */
  w03  = (w05*w09);
  /* #251: @7 = @0[12] */
  w07 = wr00[12];
  /* #252: @6 = @2[1] */
  for (rr=(&w06), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #253: @4 = (@7*@6) */
  w04  = (w07*w06);
  /* #254: @3 = (@3-@4) */
  w03 -= w04;
  /* #255: @4 = @2[0] */
  for (rr=(&w04), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #256: @7 = (@7*@4) */
  w07 *= w04;
  /* #257: @10 = @0[10] */
  w10 = wr00[10];
  /* #258: @9 = (@10*@9) */
  w09  = (w10*w09);
  /* #259: @7 = (@7-@9) */
  w07 -= w09;
  /* #260: @10 = (@10*@6) */
  w10 *= w06;
  /* #261: @5 = (@5*@4) */
  w05 *= w04;
  /* #262: @10 = (@10-@5) */
  w10 -= w05;
  /* #263: @2 = vertcat(@3, @7, @10) */
  rr=w02;
  *rr++ = w03;
  *rr++ = w07;
  *rr++ = w10;
  /* #264: @1 = (@1-@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) -= (*cs++);
  /* #265: @15 = 
  [[0.034393, 0, 0], 
   [0, 0.0391674, 0], 
   [0, 0, 0.028093]] */
  wr15 = casadi_c10;
  /* #266: @1 = (@15\@1) */
  rr = w01;
  ss = wr15;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #267: output[0][3] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+10);
  /* #268: @3 = input[2][0] */
  w03 = arg[2] ? arg[2][0] : 0;
  /* #269: @7 = 100 */
  w07 = 100.;
  /* #270: @24 = input[1][0] */
  casadi_copy(arg[1], 5, w24);
  /* #271: @10 = @24[0] */
  for (rr=(&w10), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #272: @5 = 0 */
  w05 = 0.;
  /* #273: @10 = fmax(@10,@5) */
  w10  = casadi_fmax(w10,w05);
  /* #274: @5 = 100 */
  w05 = 100.;
  /* #275: @10 = fmin(@10,@5) */
  w10  = casadi_fmin(w10,w05);
  /* #276: @7 = (@7<@10) */
  w07  = (w07<w10);
  /* #277: @5 = 27 */
  w05 = 27.;
  /* #278: @5 = (@7?@5:0) */
  w05  = (w07?w05:0);
  /* #279: @7 = (!@7) */
  w07 = (! w07 );
  /* #280: @4 = 0 */
  w04 = 0.;
  /* #281: @4 = (@10<@4) */
  w04  = (w10<w04);
  /* #282: @4 = (!@4) */
  w04 = (! w04 );
  /* #283: @6 = 90 */
  w06 = 90.;
  /* #284: @6 = (@6<=@10) */
  w06  = (w06<=w10);
  /* #285: @9 = 100 */
  w09 = 100.;
  /* #286: @9 = (@10<=@9) */
  w09  = (w10<=w09);
  /* #287: @6 = (@6&&@9) */
  w06  = (w06&&w09);
  /* #288: @9 = 26.753 */
  w09 = 2.6752962991109627e+01;
  /* #289: @17 = 0.0247037 */
  w17 = 2.4703700889037349e-02;
  /* #290: @25 = 90 */
  w25 = 90.;
  /* #291: @25 = (@10-@25) */
  w25  = (w10-w25);
  /* #292: @17 = (@17*@25) */
  w17 *= w25;
  /* #293: @9 = (@9+@17) */
  w09 += w17;
  /* #294: @9 = (@6?@9:0) */
  w09  = (w06?w09:0);
  /* #295: @6 = (!@6) */
  w06 = (! w06 );
  /* #296: @17 = 85 */
  w17 = 85.;
  /* #297: @17 = (@17<=@10) */
  w17  = (w17<=w10);
  /* #298: @25 = 90 */
  w25 = 90.;
  /* #299: @25 = (@10<=@25) */
  w25  = (w10<=w25);
  /* #300: @17 = (@17&&@25) */
  w17  = (w17&&w25);
  /* #301: @25 = 24.7588 */
  w25 = 2.4758844578012344e+01;
  /* #302: @26 = 0.398824 */
  w26 = 3.9882368261945655e-01;
  /* #303: @27 = 85 */
  w27 = 85.;
  /* #304: @27 = (@10-@27) */
  w27  = (w10-w27);
  /* #305: @26 = (@26*@27) */
  w26 *= w27;
  /* #306: @25 = (@25+@26) */
  w25 += w26;
  /* #307: @25 = (@17?@25:0) */
  w25  = (w17?w25:0);
  /* #308: @17 = (!@17) */
  w17 = (! w17 );
  /* #309: @26 = 80 */
  w26 = 80.;
  /* #310: @26 = (@26<=@10) */
  w26  = (w26<=w10);
  /* #311: @27 = 85 */
  w27 = 85.;
  /* #312: @27 = (@10<=@27) */
  w27  = (w10<=w27);
  /* #313: @26 = (@26&&@27) */
  w26  = (w26&&w27);
  /* #314: @27 = 22.8389 */
  w27 = 2.2838908040823828e+01;
  /* #315: @28 = 0.383987 */
  w28 = 3.8398730743770315e-01;
  /* #316: @29 = 80 */
  w29 = 80.;
  /* #317: @29 = (@10-@29) */
  w29  = (w10-w29);
  /* #318: @28 = (@28*@29) */
  w28 *= w29;
  /* #319: @27 = (@27+@28) */
  w27 += w28;
  /* #320: @27 = (@26?@27:0) */
  w27  = (w26?w27:0);
  /* #321: @26 = (!@26) */
  w26 = (! w26 );
  /* #322: @28 = 75 */
  w28 = 75.;
  /* #323: @28 = (@28<=@10) */
  w28  = (w28<=w10);
  /* #324: @29 = 80 */
  w29 = 80.;
  /* #325: @29 = (@10<=@29) */
  w29  = (w10<=w29);
  /* #326: @28 = (@28&&@29) */
  w28  = (w28&&w29);
  /* #327: @29 = 20.8242 */
  w29 = 2.0824175499723022e+01;
  /* #328: @30 = 0.402947 */
  w30 = 4.0294650822016109e-01;
  /* #329: @31 = 75 */
  w31 = 75.;
  /* #330: @31 = (@10-@31) */
  w31  = (w10-w31);
  /* #331: @30 = (@30*@31) */
  w30 *= w31;
  /* #332: @29 = (@29+@30) */
  w29 += w30;
  /* #333: @29 = (@28?@29:0) */
  w29  = (w28?w29:0);
  /* #334: @28 = (!@28) */
  w28 = (! w28 );
  /* #335: @30 = 70 */
  w30 = 70.;
  /* #336: @30 = (@30<=@10) */
  w30  = (w30<=w10);
  /* #337: @31 = 75 */
  w31 = 75.;
  /* #338: @31 = (@10<=@31) */
  w31  = (w10<=w31);
  /* #339: @30 = (@30&&@31) */
  w30  = (w30&&w31);
  /* #340: @31 = 18.3959 */
  w31 = 1.8395945471821904e+01;
  /* #341: @32 = 0.485646 */
  w32 = 4.8564600558022375e-01;
  /* #342: @33 = 70 */
  w33 = 70.;
  /* #343: @33 = (@10-@33) */
  w33  = (w10-w33);
  /* #344: @32 = (@32*@33) */
  w32 *= w33;
  /* #345: @31 = (@31+@32) */
  w31 += w32;
  /* #346: @31 = (@30?@31:0) */
  w31  = (w30?w31:0);
  /* #347: @30 = (!@30) */
  w30 = (! w30 );
  /* #348: @32 = 60 */
  w32 = 60.;
  /* #349: @32 = (@32<=@10) */
  w32  = (w32<=w10);
  /* #350: @33 = 70 */
  w33 = 70.;
  /* #351: @33 = (@10<=@33) */
  w33  = (w10<=w33);
  /* #352: @32 = (@32&&@33) */
  w32  = (w32&&w33);
  /* #353: @33 = 14.7408 */
  w33 = 1.4740834272959603e+01;
  /* #354: @34 = 0.365511 */
  w34 = 3.6551111988623008e-01;
  /* #355: @35 = 60 */
  w35 = 60.;
  /* #356: @35 = (@10-@35) */
  w35  = (w10-w35);
  /* #357: @34 = (@34*@35) */
  w34 *= w35;
  /* #358: @33 = (@33+@34) */
  w33 += w34;
  /* #359: @33 = (@32?@33:0) */
  w33  = (w32?w33:0);
  /* #360: @32 = (!@32) */
  w32 = (! w32 );
  /* #361: @34 = 50 */
  w34 = 50.;
  /* #362: @34 = (@34<=@10) */
  w34  = (w34<=w10);
  /* #363: @35 = 60 */
  w35 = 60.;
  /* #364: @35 = (@10<=@35) */
  w35  = (w10<=w35);
  /* #365: @34 = (@34&&@35) */
  w34  = (w34&&w35);
  /* #366: @35 = 12.0425 */
  w35 = 1.2042451609558308e+01;
  /* #367: @36 = 0.269838 */
  w36 = 2.6983826634012953e-01;
  /* #368: @37 = 50 */
  w37 = 50.;
  /* #369: @37 = (@10-@37) */
  w37  = (w10-w37);
  /* #370: @36 = (@36*@37) */
  w36 *= w37;
  /* #371: @35 = (@35+@36) */
  w35 += w36;
  /* #372: @35 = (@34?@35:0) */
  w35  = (w34?w35:0);
  /* #373: @34 = (!@34) */
  w34 = (! w34 );
  /* #374: @36 = 40 */
  w36 = 40.;
  /* #375: @36 = (@36<=@10) */
  w36  = (w36<=w10);
  /* #376: @37 = 50 */
  w37 = 50.;
  /* #377: @37 = (@10<=@37) */
  w37  = (w10<=w37);
  /* #378: @36 = (@36&&@37) */
  w36  = (w36&&w37);
  /* #379: @37 = 9.61328 */
  w37 = 9.6132801575173321e+00;
  /* #380: @38 = 0.242917 */
  w38 = 2.4291714520409755e-01;
  /* #381: @39 = 40 */
  w39 = 40.;
  /* #382: @39 = (@10-@39) */
  w39  = (w10-w39);
  /* #383: @38 = (@38*@39) */
  w38 *= w39;
  /* #384: @37 = (@37+@38) */
  w37 += w38;
  /* #385: @37 = (@36?@37:0) */
  w37  = (w36?w37:0);
  /* #386: @36 = (!@36) */
  w36 = (! w36 );
  /* #387: @38 = 30 */
  w38 = 30.;
  /* #388: @38 = (@38<=@10) */
  w38  = (w38<=w10);
  /* #389: @39 = 40 */
  w39 = 40.;
  /* #390: @39 = (@10<=@39) */
  w39  = (w10<=w39);
  /* #391: @38 = (@38&&@39) */
  w38  = (w38&&w39);
  /* #392: @39 = 7.04574 */
  w39 = 7.0457390494971124e+00;
  /* #393: @40 = 0.256754 */
  w40 = 2.5675411080202198e-01;
  /* #394: @41 = 30 */
  w41 = 30.;
  /* #395: @41 = (@10-@41) */
  w41  = (w10-w41);
  /* #396: @40 = (@40*@41) */
  w40 *= w41;
  /* #397: @39 = (@39+@40) */
  w39 += w40;
  /* #398: @39 = (@38?@39:0) */
  w39  = (w38?w39:0);
  /* #399: @38 = (!@38) */
  w38 = (! w38 );
  /* #400: @40 = 20 */
  w40 = 20.;
  /* #401: @40 = (@40<=@10) */
  w40  = (w40<=w10);
  /* #402: @41 = 30 */
  w41 = 30.;
  /* #403: @41 = (@10<=@41) */
  w41  = (w10<=w41);
  /* #404: @40 = (@40&&@41) */
  w40  = (w40&&w41);
  /* #405: @41 = 4.24854 */
  w41 = 4.2485368817013320e+00;
  /* #406: @42 = 0.27972 */
  w42 = 2.7972021677957803e-01;
  /* #407: @43 = 20 */
  w43 = 20.;
  /* #408: @43 = (@10-@43) */
  w43  = (w10-w43);
  /* #409: @42 = (@42*@43) */
  w42 *= w43;
  /* #410: @41 = (@41+@42) */
  w41 += w42;
  /* #411: @41 = (@40?@41:0) */
  w41  = (w40?w41:0);
  /* #412: @40 = (!@40) */
  w40 = (! w40 );
  /* #413: @42 = 10 */
  w42 = 10.;
  /* #414: @42 = (@42<=@10) */
  w42  = (w42<=w10);
  /* #415: @43 = 20 */
  w43 = 20.;
  /* #416: @43 = (@10<=@43) */
  w43  = (w10<=w43);
  /* #417: @42 = (@42&&@43) */
  w42  = (w42&&w43);
  /* #418: @43 = 1.46239 */
  w43 = 1.4623894660200982e+00;
  /* #419: @44 = 0.278615 */
  w44 = 2.7861474156812338e-01;
  /* #420: @45 = 10 */
  w45 = 10.;
  /* #421: @45 = (@10-@45) */
  w45  = (w10-w45);
  /* #422: @44 = (@44*@45) */
  w44 *= w45;
  /* #423: @43 = (@43+@44) */
  w43 += w44;
  /* #424: @43 = (@42?@43:0) */
  w43  = (w42?w43:0);
  /* #425: @42 = (!@42) */
  w42 = (! w42 );
  /* #426: @44 = 0 */
  w44 = 0.;
  /* #427: @44 = (@44<=@10) */
  w44  = (w44<=w10);
  /* #428: @45 = 10 */
  w45 = 10.;
  /* #429: @45 = (@10<=@45) */
  w45  = (w10<=w45);
  /* #430: @44 = (@44&&@45) */
  w44  = (w44&&w45);
  /* #431: @45 = 0.146239 */
  w45 = 1.4623894660200981e-01;
  /* #432: @45 = (@45*@10) */
  w45 *= w10;
  /* #433: @44 = (@44?@45:0) */
  w44  = (w44?w45:0);
  /* #434: @42 = (@42?@44:0) */
  w42  = (w42?w44:0);
  /* #435: @43 = (@43+@42) */
  w43 += w42;
  /* #436: @40 = (@40?@43:0) */
  w40  = (w40?w43:0);
  /* #437: @41 = (@41+@40) */
  w41 += w40;
  /* #438: @38 = (@38?@41:0) */
  w38  = (w38?w41:0);
  /* #439: @39 = (@39+@38) */
  w39 += w38;
  /* #440: @36 = (@36?@39:0) */
  w36  = (w36?w39:0);
  /* #441: @37 = (@37+@36) */
  w37 += w36;
  /* #442: @34 = (@34?@37:0) */
  w34  = (w34?w37:0);
  /* #443: @35 = (@35+@34) */
  w35 += w34;
  /* #444: @32 = (@32?@35:0) */
  w32  = (w32?w35:0);
  /* #445: @33 = (@33+@32) */
  w33 += w32;
  /* #446: @30 = (@30?@33:0) */
  w30  = (w30?w33:0);
  /* #447: @31 = (@31+@30) */
  w31 += w30;
  /* #448: @28 = (@28?@31:0) */
  w28  = (w28?w31:0);
  /* #449: @29 = (@29+@28) */
  w29 += w28;
  /* #450: @26 = (@26?@29:0) */
  w26  = (w26?w29:0);
  /* #451: @27 = (@27+@26) */
  w27 += w26;
  /* #452: @17 = (@17?@27:0) */
  w17  = (w17?w27:0);
  /* #453: @25 = (@25+@17) */
  w25 += w17;
  /* #454: @6 = (@6?@25:0) */
  w06  = (w06?w25:0);
  /* #455: @9 = (@9+@6) */
  w09 += w06;
  /* #456: @4 = (@4?@9:0) */
  w04  = (w04?w09:0);
  /* #457: @7 = (@7?@4:0) */
  w07  = (w07?w04:0);
  /* #458: @5 = (@5+@7) */
  w05 += w07;
  /* #459: @3 = (@3*@5) */
  w03 *= w05;
  /* #460: @5 = (@3-@8) */
  w05  = (w03-w08);
  /* #461: @8 = (@8<@3) */
  w08  = (w08<w03);
  /* #462: @3 = 0.18 */
  w03 = 1.7999999999999999e-01;
  /* #463: @3 = (@8?@3:0) */
  w03  = (w08?w03:0);
  /* #464: @8 = (!@8) */
  w08 = (! w08 );
  /* #465: @7 = 0.22 */
  w07 = 2.2000000000000000e-01;
  /* #466: @8 = (@8?@7:0) */
  w08  = (w08?w07:0);
  /* #467: @3 = (@3+@8) */
  w03 += w08;
  /* #468: @5 = (@5/@3) */
  w05 /= w03;
  /* #469: output[0][4] = @5 */
  if (res[0]) res[0][13] = w05;
  /* #470: @5 = 3.14159 */
  w05 = 3.1415926535897931e+00;
  /* #471: @3 = @24[1] */
  for (rr=(&w03), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #472: @8 = -34 */
  w08 = -34.;
  /* #473: @3 = fmax(@3,@8) */
  w03  = casadi_fmax(w03,w08);
  /* #474: @8 = 34 */
  w08 = 34.;
  /* #475: @3 = fmin(@3,@8) */
  w03  = casadi_fmin(w03,w08);
  /* #476: @5 = (@5*@3) */
  w05 *= w03;
  /* #477: @3 = 180 */
  w03 = 180.;
  /* #478: @5 = (@5/@3) */
  w05 /= w03;
  /* #479: @3 = @0[14] */
  w03 = wr00[14];
  /* #480: @5 = (@5-@3) */
  w05 -= w03;
  /* #481: @3 = 0.07 */
  w03 = 7.0000000000000007e-02;
  /* #482: @5 = (@5/@3) */
  w05 /= w03;
  /* #483: output[0][5] = @5 */
  if (res[0]) res[0][14] = w05;
  /* #484: @5 = 3.14159 */
  w05 = 3.1415926535897931e+00;
  /* #485: @3 = @24[2] */
  for (rr=(&w03), cs=w24+2; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #486: @8 = -34 */
  w08 = -34.;
  /* #487: @3 = fmax(@3,@8) */
  w03  = casadi_fmax(w03,w08);
  /* #488: @8 = 34 */
  w08 = 34.;
  /* #489: @3 = fmin(@3,@8) */
  w03  = casadi_fmin(w03,w08);
  /* #490: @5 = (@5*@3) */
  w05 *= w03;
  /* #491: @3 = 180 */
  w03 = 180.;
  /* #492: @5 = (@5/@3) */
  w05 /= w03;
  /* #493: @3 = @0[15] */
  w03 = wr00[15];
  /* #494: @5 = (@5-@3) */
  w05 -= w03;
  /* #495: @3 = 0.07 */
  w03 = 7.0000000000000007e-02;
  /* #496: @5 = (@5/@3) */
  w05 /= w03;
  /* #497: output[0][6] = @5 */
  if (res[0]) res[0][15] = w05;
  /* #498: @5 = 3.14159 */
  w05 = 3.1415926535897931e+00;
  /* #499: @3 = @24[3] */
  for (rr=(&w03), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #500: @8 = -34 */
  w08 = -34.;
  /* #501: @3 = fmax(@3,@8) */
  w03  = casadi_fmax(w03,w08);
  /* #502: @8 = 34 */
  w08 = 34.;
  /* #503: @3 = fmin(@3,@8) */
  w03  = casadi_fmin(w03,w08);
  /* #504: @5 = (@5*@3) */
  w05 *= w03;
  /* #505: @3 = 180 */
  w03 = 180.;
  /* #506: @5 = (@5/@3) */
  w05 /= w03;
  /* #507: @3 = @0[16] */
  w03 = wr00[16];
  /* #508: @5 = (@5-@3) */
  w05 -= w03;
  /* #509: @3 = 0.07 */
  w03 = 7.0000000000000007e-02;
  /* #510: @5 = (@5/@3) */
  w05 /= w03;
  /* #511: output[0][7] = @5 */
  if (res[0]) res[0][16] = w05;
  /* #512: @5 = 3.14159 */
  w05 = 3.1415926535897931e+00;
  /* #513: @3 = @24[4] */
  for (rr=(&w03), cs=w24+4; cs!=w24+5; cs+=1) *rr++ = *cs;
  /* #514: @8 = -34 */
  w08 = -34.;
  /* #515: @3 = fmax(@3,@8) */
  w03  = casadi_fmax(w03,w08);
  /* #516: @8 = 34 */
  w08 = 34.;
  /* #517: @3 = fmin(@3,@8) */
  w03  = casadi_fmin(w03,w08);
  /* #518: @5 = (@5*@3) */
  w05 *= w03;
  /* #519: @3 = 180 */
  w03 = 180.;
  /* #520: @5 = (@5/@3) */
  w05 /= w03;
  /* #521: @3 = @0[17] */
  w03 = wr00[17];
  /* #522: @5 = (@5-@3) */
  w05 -= w03;
  /* #523: @3 = 0.07 */
  w03 = 7.0000000000000007e-02;
  /* #524: @5 = (@5/@3) */
  w05 /= w03;
  /* #525: output[0][8] = @5 */
  if (res[0]) res[0][17] = w05;
  return 0;
}

/* amon_model_expl_ode_fun:(i0[18],i1[5],i2)->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w1=w+160, w2, *w3=w+166;
  const casadi_real **arg1=arg+3, *wr0;
  /* #0: @0 = input[0][0] */
  wr0 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 5, w1);
  /* #2: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = f(@0, @1, @2) */
  arg1[0]=wr0;
  arg1[1]=w1;
  arg1[2]=(&w2);
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][0] = @3 */
  casadi_copy(w3, 18, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void amon_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void amon_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void amon_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void amon_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int amon_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int amon_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real amon_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* amon_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* amon_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* amon_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* amon_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 184;
  return 0;
}

CASADI_SYMBOL_EXPORT int amon_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 184*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
